In [1]:
import pandas as pd

data = pd.read_csv('Power_Query.csv')
data

,Customer ID,Customer Name,Region,Customer Segment,Sales Stage,Sales Date,Product,Category,Country,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date
0,1,alice johnson,NORTH,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026
1,2,BOB SMITH,South,Corporate,Qualified,08-01-2026,Office Chair,Furniture,India,18000.0,12000,0.33,Target,Medium,Closed Won,Retail,15-01-2026
2,3,Carol Davis,east,consumer,Negotiation,10-01-2026,Mobile Phone,electronics,India,32000.0,35000,-0.09,Below Target,Low,Closed Lost,Online,NaN
3,4,david lee,West,Corporate,Proposal,12-01-2026,Desk,Furniture,India,22000.0,15000,0.32,Target,Medium,Open,Retail,20-01-2026
4,5,EMILY BROWN,North,SMB,Prospecting,15-01-2026,Monitor,Electronics,India,15000.0,9000,0.40,Target,High,Open,Online,NaN
5,6,Frank Wilson,south,Consumer,Qualified,18-01-2026,Printer,electronics,India,12500.0,8000,0.36,Target,Medium,Closed Won,Retail,25-01-2026
6,7,grace miller,EAST,corporate,Negotiation,20-01-2026,Laptop,Electronics,India,58000.0,47000,0.19,Target,High,Closed Won,Online,28-01-2026
7,8,Henry Moore,west,SMB,Proposal,22-01-2026,Table,Furniture,India,26000.0,18000,0.31,Target,Medium,Open,Retail,NaN
8,9,Irene Taylor,NaN,consumer,Qualified,25-01-2026,Headphones,Electronics,India,8000.0,5000,0.38,Below Target,Low,Closed Lost,Online,02-02-2026
9,10,jack anderson,South,Corporate,Negotiation,28-01-2026,Sofa,Furniture,India,45000.0,30000,0.33,Target,High,Closed Won,Retail,05-02-2026
10,11,Karen Thomas,east,smb,Prospecting,01-02-2026,Keyboard,electronics,India,4500.0,2500,0.44,Target,Medium,Open,Online,NaN
11,12,Liam Jackson,West,Consumer,Qualified,03-02-2026,Tablet,Electronics,India,28000.0,19000,0.32,Target,High,Closed Won,Retail,10-02-2026
12,13,Mia White,North,Corporate,Proposal,05-02-2026,Cabinet,Furniture,India,30000.0,21000,0.30,Target,Medium,Open,Retail,NaN
13,14,NOAH HARRIS,South,consumer,Negotiation,08-02-2026,Smart Watch,Electronics,India,12000.0,7000,0.42,Below Target,Low,Closed Lost,Online,15-02-2026
14,15,Olivia Martin,East,SMB,Prospecting,10-02-2026,Mouse,Electronics,India,2500.0,1200,0.52,Target,Low,Open,Online,NaN
15,16,Peter Thompson,West,Corporate,Qualified,12-02-2026,Conference Table,Furniture,India,65000.0,45000,0.31,Target,High,Closed Won,Retail,20-02-2026
16,17,Quinn Garcia,North,Consumer,Proposal,15-02-2026,Camera,Electronics,India,40000.0,28000,0.30,Target,Medium,Open,Online,NaN
17,18,Rachel Martinez,South,Corporate,Negotiation,18-02-2026,Bookshelf,Furniture,India,14000.0,9000,0.36,Target,Medium,Closed Won,Retail,25-02-2026
18,19,Sam Robinson,East,SMB,Qualified,20-02-2026,Webcam,Electronics,India,NaN,4200,0.40,Below Target,Low,Closed Lost,Online,27-02-2026
19,20,Tina Clark,West,consumer,Prospecting,22-02-2026,Desk Lamp,Furniture,India,5500.0,3000,0.45,Target,Low,Open,Retail,NaN
20,21,Uma Rodriguez,North,Corporate,Qualified,25-02-2026,Laptop,Electronics,India,62000.0,48000,0.23,Target,High,Closed Won,Online,03-03-2026
21,22,Victor Lewis,South,SMB,Proposal,28-02-2026,Office Chair,Furniture,India,20000.0,13500,0.33,Target,Medium,Open,Retail,NaN
22,23,Wendy Lee,East,Consumer,Negotiation,02-03-2026,Mobile Phone,Electronics,India,35000.0,24000,0.31,Target,High,Closed Won,Online,09-03-2026
23,24,xavier walker,West,Corporate,prospecting,05-03-2026,Printer,Electronics,India,13000.0,8000,0.38,Below Target,Low,Open,Retail,NaN
24,25,Yara Hall,North,SMB,Qualified,08-03-2026,Monitor,Electronics,India,17000.0,10000,0.41,Target,Medium,Closed Won,Online,15-03-2026
25,26,Zach Allen,South,Consumer,Proposal,10-03-2026,Dining Table,Furniture,India,38000.0,25000,0.34,Target,Medium,Open,Retail,NaN
26,27,alice johnson,north,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026
27,28,Ben Young,East,Corporate,Negotiation,15-03-2026,Projector,electronics,India,27000.0,16000,0.41,Below Target,Low,Closed Lost,Online,22-03-2026
28,29,Chloe King,West,SMB,Qualified,18-03-2026,Keyboard,Electronics,India,5000.0,2800,0.44,Target,Low,Open,Online,NaN
29,30,Daniel Wright,North,Corporate,Proposal,20-03-2026,sofa,Furniture,India,48000.0,32000,0.33,Target,High,Closed Won,Retail,28-03-2026
30,31,Eva Lopez,South,Consumer,Negotiation,22-03-2026,Tablet,Electronics,India,30000.0,20500,0.32,Target,Medium,Closed Won,Online,30-03-2026
31,32,Finn Hill,East,SMB,Prospecting,25-03-2026,Mouse,Electronics,India,2800.0,1300,0.54,Below Target,Low,Open,Online,NaN
32,33,Gina Scott,West,Corporate,Qualified,28-03-2026,Cabinet,Furniture,India,32000.0,22000,0.31,Target,Medium,Closed Won,Retail,05-04-2026
33,34,Harry Green,North,Consumer,Proposal,30-03-2026,Camera,ELECTRONICS,India,42000.0,29000,0.31,Target,High,Open,Online,NaN
34,35,Isla Adams,South,Corporate,Negotiation,02-04-2026,Conference Table,Furniture,India,68000.0,46000,0.32,Target,High,Closed Won,Retail,10-04-2026
35,36,Jon Baker,East,SMB,Qualified,05-04-2026,Headphones,Electronics,India,9000.0,5200,0.42,Below Target,Low,Closed Lost,Online,12-04-2026
36,37,Kara Nelson,West,Consumer,Prospecting,08-04-2026,Desk,Furniture,India,24000.0,16000,0.33,Target,Medium,Open,Retail,NaN
37,38,Leo Carter,North,Corporate,Qualified,10-04-2026,Smart Watch,Electronics,India,13500.0,7600,0.44,Target,Medium,Closed Won,Online,18-04-2026
38,39,Maya Mitchell,South,SMB,Proposal,12-04-2026,Bookshelf,Furniture,India,15500.0,9800,0.37,Target,Medium,Open,Retail,NaN
39,40,Nate Perez,East,Consumer,Negotiation,15-04-2026,Webcam,Electronics,India,7500.0,4500,0.40,Below Target,Low,Closed Lost,Online,22-04-2026
40,41,Owen Roberts,West,Corporate,Qualified,18-04-2026,Laptop,Electronics,India,60000.0,45500,0.24,Target,High,Closed Won,Online,26-04-2026
41,42,Paula Turner,north,SMB,Prospecting,20-04-2026,Office Chair,Furniture,India,19000.0,12500,0.34,Target,Medium,Open,Retail,NaN
42,43,Reed Phillips,South,Consumer,Proposal,22-04-2026,Mobile Phone,Electronics,India,33000.0,23000,0.30,Target,High,Closed Won,Online,30-04-2026
43,44,Sara Campbell,East,Corporate,Negotiation,not available,Printer,Electronics,India,14000.0,8500,0.39,Below Target,Low,Closed Lost,Retail,02-05-2026
44,45,Tom Parker,West,SMB,Qualified,28-04-2026,Monitor,Electronics,India,16000.0,9500,0.41,Target,Medium,Closed Won,Online,05-05-2026
45,46,Usha Evans,North,Consumer,Prospecting,01-05-2026,Dining Table,Furniture,India,40000.0,27000,0.33,Target,Medium,Open,Retail,NaN
46,47,Vikram Edwards,South,Corporate,Qualified,03-05-2026,Projector,Electronics,India,29000.0,17000,0.41,Target,High,Closed Won,online,10-05-2026
47,48,Willa Collins,East,SMB,Proposal,05-05-2026,Keyboard,Electronics,India,5200.0,3000,NaN,Below Target,Low,Open,Online,NaN
48,49,Yusuf Stewart,West,Consumer,Negotiation,08-05-2026,Sofa,Furniture,India,50000.0,34000,0.32,Target,High,Closed Won,Retail,15-05-2026
49,50,Zoe Sanchez,North,Corporate,Qualified,10-05-2026,Cabinet,Furniture,India,34000.0,23000,0.32,Target,Medium,Closed Won,Retail,18-05-2026

In [2]:
#filtering data

data[data['Profit Margin']>0.33]

,Customer ID,Customer Name,Region,Customer Segment,Sales Stage,Sales Date,Product,Category,Country,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date
4,5,EMILY BROWN,North,SMB,Prospecting,15-01-2026,Monitor,Electronics,India,15000.0,9000,0.40,Target,High,Open,Online,NaN
5,6,Frank Wilson,south,Consumer,Qualified,18-01-2026,Printer,electronics,India,12500.0,8000,0.36,Target,Medium,Closed Won,Retail,25-01-2026
8,9,Irene Taylor,NaN,consumer,Qualified,25-01-2026,Headphones,Electronics,India,8000.0,5000,0.38,Below Target,Low,Closed Lost,Online,02-02-2026
10,11,Karen Thomas,east,smb,Prospecting,01-02-2026,Keyboard,electronics,India,4500.0,2500,0.44,Target,Medium,Open,Online,NaN
13,14,NOAH HARRIS,South,consumer,Negotiation,08-02-2026,Smart Watch,Electronics,India,12000.0,7000,0.42,Below Target,Low,Closed Lost,Online,15-02-2026
14,15,Olivia Martin,East,SMB,Prospecting,10-02-2026,Mouse,Electronics,India,2500.0,1200,0.52,Target,Low,Open,Online,NaN
17,18,Rachel Martinez,South,Corporate,Negotiation,18-02-2026,Bookshelf,Furniture,India,14000.0,9000,0.36,Target,Medium,Closed Won,Retail,25-02-2026
18,19,Sam Robinson,East,SMB,Qualified,20-02-2026,Webcam,Electronics,India,NaN,4200,0.40,Below Target,Low,Closed Lost,Online,27-02-2026
19,20,Tina Clark,West,consumer,Prospecting,22-02-2026,Desk Lamp,Furniture,India,5500.0,3000,0.45,Target,Low,Open,Retail,NaN
23,24,xavier walker,West,Corporate,prospecting,05-03-2026,Printer,Electronics,India,13000.0,8000,0.38,Below Target,Low,Open,Retail,NaN
24,25,Yara Hall,North,SMB,Qualified,08-03-2026,Monitor,Electronics,India,17000.0,10000,0.41,Target,Medium,Closed Won,Online,15-03-2026
25,26,Zach Allen,South,Consumer,Proposal,10-03-2026,Dining Table,Furniture,India,38000.0,25000,0.34,Target,Medium,Open,Retail,NaN
27,28,Ben Young,East,Corporate,Negotiation,15-03-2026,Projector,electronics,India,27000.0,16000,0.41,Below Target,Low,Closed Lost,Online,22-03-2026
28,29,Chloe King,West,SMB,Qualified,18-03-2026,Keyboard,Electronics,India,5000.0,2800,0.44,Target,Low,Open,Online,NaN
31,32,Finn Hill,East,SMB,Prospecting,25-03-2026,Mouse,Electronics,India,2800.0,1300,0.54,Below Target,Low,Open,Online,NaN
35,36,Jon Baker,East,SMB,Qualified,05-04-2026,Headphones,Electronics,India,9000.0,5200,0.42,Below Target,Low,Closed Lost,Online,12-04-2026
37,38,Leo Carter,North,Corporate,Qualified,10-04-2026,Smart Watch,Electronics,India,13500.0,7600,0.44,Target,Medium,Closed Won,Online,18-04-2026
38,39,Maya Mitchell,South,SMB,Proposal,12-04-2026,Bookshelf,Furniture,India,15500.0,9800,0.37,Target,Medium,Open,Retail,NaN
39,40,Nate Perez,East,Consumer,Negotiation,15-04-2026,Webcam,Electronics,India,7500.0,4500,0.40,Below Target,Low,Closed Lost,Online,22-04-2026
41,42,Paula Turner,north,SMB,Prospecting,20-04-2026,Office Chair,Furniture,India,19000.0,12500,0.34,Target,Medium,Open,Retail,NaN
43,44,Sara Campbell,East,Corporate,Negotiation,not available,Printer,Electronics,India,14000.0,8500,0.39,Below Target,Low,Closed Lost,Retail,02-05-2026
44,45,Tom Parker,West,SMB,Qualified,28-04-2026,Monitor,Electronics,India,16000.0,9500,0.41,Target,Medium,Closed Won,Online,05-05-2026
46,47,Vikram Edwards,South,Corporate,Qualified,03-05-2026,Projector,Electronics,India,29000.0,17000,0.41,Target,High,Closed Won,online,10-05-2026

In [4]:
data[data['Category'] == 'Electronics']

,Customer ID,Customer Name,Region,Customer Segment,Sales Stage,Sales Date,Product,Category,Country,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date
0,1,alice johnson,NORTH,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026
4,5,EMILY BROWN,North,SMB,Prospecting,15-01-2026,Monitor,Electronics,India,15000.0,9000,0.40,Target,High,Open,Online,NaN
6,7,grace miller,EAST,corporate,Negotiation,20-01-2026,Laptop,Electronics,India,58000.0,47000,0.19,Target,High,Closed Won,Online,28-01-2026
8,9,Irene Taylor,NaN,consumer,Qualified,25-01-2026,Headphones,Electronics,India,8000.0,5000,0.38,Below Target,Low,Closed Lost,Online,02-02-2026
11,12,Liam Jackson,West,Consumer,Qualified,03-02-2026,Tablet,Electronics,India,28000.0,19000,0.32,Target,High,Closed Won,Retail,10-02-2026
13,14,NOAH HARRIS,South,consumer,Negotiation,08-02-2026,Smart Watch,Electronics,India,12000.0,7000,0.42,Below Target,Low,Closed Lost,Online,15-02-2026
14,15,Olivia Martin,East,SMB,Prospecting,10-02-2026,Mouse,Electronics,India,2500.0,1200,0.52,Target,Low,Open,Online,NaN
16,17,Quinn Garcia,North,Consumer,Proposal,15-02-2026,Camera,Electronics,India,40000.0,28000,0.30,Target,Medium,Open,Online,NaN
18,19,Sam Robinson,East,SMB,Qualified,20-02-2026,Webcam,Electronics,India,NaN,4200,0.40,Below Target,Low,Closed Lost,Online,27-02-2026
20,21,Uma Rodriguez,North,Corporate,Qualified,25-02-2026,Laptop,Electronics,India,62000.0,48000,0.23,Target,High,Closed Won,Online,03-03-2026
22,23,Wendy Lee,East,Consumer,Negotiation,02-03-2026,Mobile Phone,Electronics,India,35000.0,24000,0.31,Target,High,Closed Won,Online,09-03-2026
23,24,xavier walker,West,Corporate,prospecting,05-03-2026,Printer,Electronics,India,13000.0,8000,0.38,Below Target,Low,Open,Retail,NaN
24,25,Yara Hall,North,SMB,Qualified,08-03-2026,Monitor,Electronics,India,17000.0,10000,0.41,Target,Medium,Closed Won,Online,15-03-2026
26,27,alice johnson,north,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026
28,29,Chloe King,West,SMB,Qualified,18-03-2026,Keyboard,Electronics,India,5000.0,2800,0.44,Target,Low,Open,Online,NaN
30,31,Eva Lopez,South,Consumer,Negotiation,22-03-2026,Tablet,Electronics,India,30000.0,20500,0.32,Target,Medium,Closed Won,Online,30-03-2026
31,32,Finn Hill,East,SMB,Prospecting,25-03-2026,Mouse,Electronics,India,2800.0,1300,0.54,Below Target,Low,Open,Online,NaN
35,36,Jon Baker,East,SMB,Qualified,05-04-2026,Headphones,Electronics,India,9000.0,5200,0.42,Below Target,Low,Closed Lost,Online,12-04-2026
37,38,Leo Carter,North,Corporate,Qualified,10-04-2026,Smart Watch,Electronics,India,13500.0,7600,0.44,Target,Medium,Closed Won,Online,18-04-2026
39,40,Nate Perez,East,Consumer,Negotiation,15-04-2026,Webcam,Electronics,India,7500.0,4500,0.40,Below Target,Low,Closed Lost,Online,22-04-2026
40,41,Owen Roberts,West,Corporate,Qualified,18-04-2026,Laptop,Electronics,India,60000.0,45500,0.24,Target,High,Closed Won,Online,26-04-2026
42,43,Reed Phillips,South,Consumer,Proposal,22-04-2026,Mobile Phone,Electronics,India,33000.0,23000,0.30,Target,High,Closed Won,Online,30-04-2026
43,44,Sara Campbell,East,Corporate,Negotiation,not available,Printer,Electronics,India,14000.0,8500,0.39,Below Target,Low,Closed Lost,Retail,02-05-2026
44,45,Tom Parker,West,SMB,Qualified,28-04-2026,Monitor,Electronics,India,16000.0,9500,0.41,Target,Medium,Closed Won,Online,05-05-2026
46,47,Vikram Edwards,South,Corporate,Qualified,03-05-2026,Projector,Electronics,India,29000.0,17000,0.41,Target,High,Closed Won,online,10-05-2026
47,48,Willa Collins,East,SMB,Proposal,05-05-2026,Keyboard,Electronics,India,5200.0,3000,NaN,Below Target,Low,Open,Online,NaN

In [5]:
data[(data['Profit Margin']>0.33) & (data['Category'] == 'Electronics')]

,Customer ID,Customer Name,Region,Customer Segment,Sales Stage,Sales Date,Product,Category,Country,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date
4,5,EMILY BROWN,North,SMB,Prospecting,15-01-2026,Monitor,Electronics,India,15000.0,9000,0.40,Target,High,Open,Online,NaN
8,9,Irene Taylor,NaN,consumer,Qualified,25-01-2026,Headphones,Electronics,India,8000.0,5000,0.38,Below Target,Low,Closed Lost,Online,02-02-2026
13,14,NOAH HARRIS,South,consumer,Negotiation,08-02-2026,Smart Watch,Electronics,India,12000.0,7000,0.42,Below Target,Low,Closed Lost,Online,15-02-2026
14,15,Olivia Martin,East,SMB,Prospecting,10-02-2026,Mouse,Electronics,India,2500.0,1200,0.52,Target,Low,Open,Online,NaN
18,19,Sam Robinson,East,SMB,Qualified,20-02-2026,Webcam,Electronics,India,NaN,4200,0.40,Below Target,Low,Closed Lost,Online,27-02-2026
23,24,xavier walker,West,Corporate,prospecting,05-03-2026,Printer,Electronics,India,13000.0,8000,0.38,Below Target,Low,Open,Retail,NaN
24,25,Yara Hall,North,SMB,Qualified,08-03-2026,Monitor,Electronics,India,17000.0,10000,0.41,Target,Medium,Closed Won,Online,15-03-2026
28,29,Chloe King,West,SMB,Qualified,18-03-2026,Keyboard,Electronics,India,5000.0,2800,0.44,Target,Low,Open,Online,NaN
31,32,Finn Hill,East,SMB,Prospecting,25-03-2026,Mouse,Electronics,India,2800.0,1300,0.54,Below Target,Low,Open,Online,NaN
35,36,Jon Baker,East,SMB,Qualified,05-04-2026,Headphones,Electronics,India,9000.0,5200,0.42,Below Target,Low,Closed Lost,Online,12-04-2026
37,38,Leo Carter,North,Corporate,Qualified,10-04-2026,Smart Watch,Electronics,India,13500.0,7600,0.44,Target,Medium,Closed Won,Online,18-04-2026
39,40,Nate Perez,East,Consumer,Negotiation,15-04-2026,Webcam,Electronics,India,7500.0,4500,0.40,Below Target,Low,Closed Lost,Online,22-04-2026
43,44,Sara Campbell,East,Corporate,Negotiation,not available,Printer,Electronics,India,14000.0,8500,0.39,Below Target,Low,Closed Lost,Retail,02-05-2026
44,45,Tom Parker,West,SMB,Qualified,28-04-2026,Monitor,Electronics,India,16000.0,9500,0.41,Target,Medium,Closed Won,Online,05-05-2026
46,47,Vikram Edwards,South,Corporate,Qualified,03-05-2026,Projector,Electronics,India,29000.0,17000,0.41,Target,High,Closed Won,online,10-05-2026

In [10]:
#sorting
data.sort_values("Customer ID",ascending = True)

,Customer ID,Customer Name,Region,Customer Segment,Sales Stage,Sales Date,Product,Category,Country,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date
0,1,alice johnson,NORTH,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026
1,2,BOB SMITH,South,Corporate,Qualified,08-01-2026,Office Chair,Furniture,India,18000.0,12000,0.33,Target,Medium,Closed Won,Retail,15-01-2026
2,3,Carol Davis,east,consumer,Negotiation,10-01-2026,Mobile Phone,electronics,India,32000.0,35000,-0.09,Below Target,Low,Closed Lost,Online,NaN
3,4,david lee,West,Corporate,Proposal,12-01-2026,Desk,Furniture,India,22000.0,15000,0.32,Target,Medium,Open,Retail,20-01-2026
4,5,EMILY BROWN,North,SMB,Prospecting,15-01-2026,Monitor,Electronics,India,15000.0,9000,0.40,Target,High,Open,Online,NaN
5,6,Frank Wilson,south,Consumer,Qualified,18-01-2026,Printer,electronics,India,12500.0,8000,0.36,Target,Medium,Closed Won,Retail,25-01-2026
6,7,grace miller,EAST,corporate,Negotiation,20-01-2026,Laptop,Electronics,India,58000.0,47000,0.19,Target,High,Closed Won,Online,28-01-2026
7,8,Henry Moore,west,SMB,Proposal,22-01-2026,Table,Furniture,India,26000.0,18000,0.31,Target,Medium,Open,Retail,NaN
8,9,Irene Taylor,NaN,consumer,Qualified,25-01-2026,Headphones,Electronics,India,8000.0,5000,0.38,Below Target,Low,Closed Lost,Online,02-02-2026
9,10,jack anderson,South,Corporate,Negotiation,28-01-2026,Sofa,Furniture,India,45000.0,30000,0.33,Target,High,Closed Won,Retail,05-02-2026
10,11,Karen Thomas,east,smb,Prospecting,01-02-2026,Keyboard,electronics,India,4500.0,2500,0.44,Target,Medium,Open,Online,NaN
11,12,Liam Jackson,West,Consumer,Qualified,03-02-2026,Tablet,Electronics,India,28000.0,19000,0.32,Target,High,Closed Won,Retail,10-02-2026
12,13,Mia White,North,Corporate,Proposal,05-02-2026,Cabinet,Furniture,India,30000.0,21000,0.30,Target,Medium,Open,Retail,NaN
13,14,NOAH HARRIS,South,consumer,Negotiation,08-02-2026,Smart Watch,Electronics,India,12000.0,7000,0.42,Below Target,Low,Closed Lost,Online,15-02-2026
14,15,Olivia Martin,East,SMB,Prospecting,10-02-2026,Mouse,Electronics,India,2500.0,1200,0.52,Target,Low,Open,Online,NaN
15,16,Peter Thompson,West,Corporate,Qualified,12-02-2026,Conference Table,Furniture,India,65000.0,45000,0.31,Target,High,Closed Won,Retail,20-02-2026
16,17,Quinn Garcia,North,Consumer,Proposal,15-02-2026,Camera,Electronics,India,40000.0,28000,0.30,Target,Medium,Open,Online,NaN
17,18,Rachel Martinez,South,Corporate,Negotiation,18-02-2026,Bookshelf,Furniture,India,14000.0,9000,0.36,Target,Medium,Closed Won,Retail,25-02-2026
18,19,Sam Robinson,East,SMB,Qualified,20-02-2026,Webcam,Electronics,India,NaN,4200,0.40,Below Target,Low,Closed Lost,Online,27-02-2026
19,20,Tina Clark,West,consumer,Prospecting,22-02-2026,Desk Lamp,Furniture,India,5500.0,3000,0.45,Target,Low,Open,Retail,NaN
20,21,Uma Rodriguez,North,Corporate,Qualified,25-02-2026,Laptop,Electronics,India,62000.0,48000,0.23,Target,High,Closed Won,Online,03-03-2026
21,22,Victor Lewis,South,SMB,Proposal,28-02-2026,Office Chair,Furniture,India,20000.0,13500,0.33,Target,Medium,Open,Retail,NaN
22,23,Wendy Lee,East,Consumer,Negotiation,02-03-2026,Mobile Phone,Electronics,India,35000.0,24000,0.31,Target,High,Closed Won,Online,09-03-2026
23,24,xavier walker,West,Corporate,prospecting,05-03-2026,Printer,Electronics,India,13000.0,8000,0.38,Below Target,Low,Open,Retail,NaN
24,25,Yara Hall,North,SMB,Qualified,08-03-2026,Monitor,Electronics,India,17000.0,10000,0.41,Target,Medium,Closed Won,Online,15-03-2026
25,26,Zach Allen,South,Consumer,Proposal,10-03-2026,Dining Table,Furniture,India,38000.0,25000,0.34,Target,Medium,Open,Retail,NaN
26,27,alice johnson,north,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026
27,28,Ben Young,East,Corporate,Negotiation,15-03-2026,Projector,electronics,India,27000.0,16000,0.41,Below Target,Low,Closed Lost,Online,22-03-2026
28,29,Chloe King,West,SMB,Qualified,18-03-2026,Keyboard,Electronics,India,5000.0,2800,0.44,Target,Low,Open,Online,NaN
29,30,Daniel Wright,North,Corporate,Proposal,20-03-2026,sofa,Furniture,India,48000.0,32000,0.33,Target,High,Closed Won,Retail,28-03-2026
30,31,Eva Lopez,South,Consumer,Negotiation,22-03-2026,Tablet,Electronics,India,30000.0,20500,0.32,Target,Medium,Closed Won,Online,30-03-2026
31,32,Finn Hill,East,SMB,Prospecting,25-03-2026,Mouse,Electronics,India,2800.0,1300,0.54,Below Target,Low,Open,Online,NaN
32,33,Gina Scott,West,Corporate,Qualified,28-03-2026,Cabinet,Furniture,India,32000.0,22000,0.31,Target,Medium,Closed Won,Retail,05-04-2026
33,34,Harry Green,North,Consumer,Proposal,30-03-2026,Camera,ELECTRONICS,India,42000.0,29000,0.31,Target,High,Open,Online,NaN
34,35,Isla Adams,South,Corporate,Negotiation,02-04-2026,Conference Table,Furniture,India,68000.0,46000,0.32,Target,High,Closed Won,Retail,10-04-2026
35,36,Jon Baker,East,SMB,Qualified,05-04-2026,Headphones,Electronics,India,9000.0,5200,0.42,Below Target,Low,Closed Lost,Online,12-04-2026
36,37,Kara Nelson,West,Consumer,Prospecting,08-04-2026,Desk,Furniture,India,24000.0,16000,0.33,Target,Medium,Open,Retail,NaN
37,38,Leo Carter,North,Corporate,Qualified,10-04-2026,Smart Watch,Electronics,India,13500.0,7600,0.44,Target,Medium,Closed Won,Online,18-04-2026
38,39,Maya Mitchell,South,SMB,Proposal,12-04-2026,Bookshelf,Furniture,India,15500.0,9800,0.37,Target,Medium,Open,Retail,NaN
39,40,Nate Perez,East,Consumer,Negotiation,15-04-2026,Webcam,Electronics,India,7500.0,4500,0.40,Below Target,Low,Closed Lost,Online,22-04-2026
40,41,Owen Roberts,West,Corporate,Qualified,18-04-2026,Laptop,Electronics,India,60000.0,45500,0.24,Target,High,Closed Won,Online,26-04-2026
41,42,Paula Turner,north,SMB,Prospecting,20-04-2026,Office Chair,Furniture,India,19000.0,12500,0.34,Target,Medium,Open,Retail,NaN
42,43,Reed Phillips,South,Consumer,Proposal,22-04-2026,Mobile Phone,Electronics,India,33000.0,23000,0.30,Target,High,Closed Won,Online,30-04-2026
43,44,Sara Campbell,East,Corporate,Negotiation,not available,Printer,Electronics,India,14000.0,8500,0.39,Below Target,Low,Closed Lost,Retail,02-05-2026
44,45,Tom Parker,West,SMB,Qualified,28-04-2026,Monitor,Electronics,India,16000.0,9500,0.41,Target,Medium,Closed Won,Online,05-05-2026
45,46,Usha Evans,North,Consumer,Prospecting,01-05-2026,Dining Table,Furniture,India,40000.0,27000,0.33,Target,Medium,Open,Retail,NaN
46,47,Vikram Edwards,South,Corporate,Qualified,03-05-2026,Projector,Electronics,India,29000.0,17000,0.41,Target,High,Closed Won,online,10-05-2026
47,48,Willa Collins,East,SMB,Proposal,05-05-2026,Keyboard,Electronics,India,5200.0,3000,NaN,Below Target,Low,Open,Online,NaN
48,49,Yusuf Stewart,West,Consumer,Negotiation,08-05-2026,Sofa,Furniture,India,50000.0,34000,0.32,Target,High,Closed Won,Retail,15-05-2026
49,50,Zoe Sanchez,North,Corporate,Qualified,10-05-2026,Cabinet,Furniture,India,34000.0,23000,0.32,Target,Medium,Closed Won,Retail,18-05-2026

In [11]:
data.rename(columns = {"Customer ID" : "ID"})

,ID,Customer Name,Region,Customer Segment,Sales Stage,Sales Date,Product,Category,Country,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date
0,1,alice johnson,NORTH,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026
1,2,BOB SMITH,South,Corporate,Qualified,08-01-2026,Office Chair,Furniture,India,18000.0,12000,0.33,Target,Medium,Closed Won,Retail,15-01-2026
2,3,Carol Davis,east,consumer,Negotiation,10-01-2026,Mobile Phone,electronics,India,32000.0,35000,-0.09,Below Target,Low,Closed Lost,Online,NaN
3,4,david lee,West,Corporate,Proposal,12-01-2026,Desk,Furniture,India,22000.0,15000,0.32,Target,Medium,Open,Retail,20-01-2026
4,5,EMILY BROWN,North,SMB,Prospecting,15-01-2026,Monitor,Electronics,India,15000.0,9000,0.40,Target,High,Open,Online,NaN
5,6,Frank Wilson,south,Consumer,Qualified,18-01-2026,Printer,electronics,India,12500.0,8000,0.36,Target,Medium,Closed Won,Retail,25-01-2026
6,7,grace miller,EAST,corporate,Negotiation,20-01-2026,Laptop,Electronics,India,58000.0,47000,0.19,Target,High,Closed Won,Online,28-01-2026
7,8,Henry Moore,west,SMB,Proposal,22-01-2026,Table,Furniture,India,26000.0,18000,0.31,Target,Medium,Open,Retail,NaN
8,9,Irene Taylor,NaN,consumer,Qualified,25-01-2026,Headphones,Electronics,India,8000.0,5000,0.38,Below Target,Low,Closed Lost,Online,02-02-2026
9,10,jack anderson,South,Corporate,Negotiation,28-01-2026,Sofa,Furniture,India,45000.0,30000,0.33,Target,High,Closed Won,Retail,05-02-2026
10,11,Karen Thomas,east,smb,Prospecting,01-02-2026,Keyboard,electronics,India,4500.0,2500,0.44,Target,Medium,Open,Online,NaN
11,12,Liam Jackson,West,Consumer,Qualified,03-02-2026,Tablet,Electronics,India,28000.0,19000,0.32,Target,High,Closed Won,Retail,10-02-2026
12,13,Mia White,North,Corporate,Proposal,05-02-2026,Cabinet,Furniture,India,30000.0,21000,0.30,Target,Medium,Open,Retail,NaN
13,14,NOAH HARRIS,South,consumer,Negotiation,08-02-2026,Smart Watch,Electronics,India,12000.0,7000,0.42,Below Target,Low,Closed Lost,Online,15-02-2026
14,15,Olivia Martin,East,SMB,Prospecting,10-02-2026,Mouse,Electronics,India,2500.0,1200,0.52,Target,Low,Open,Online,NaN
15,16,Peter Thompson,West,Corporate,Qualified,12-02-2026,Conference Table,Furniture,India,65000.0,45000,0.31,Target,High,Closed Won,Retail,20-02-2026
16,17,Quinn Garcia,North,Consumer,Proposal,15-02-2026,Camera,Electronics,India,40000.0,28000,0.30,Target,Medium,Open,Online,NaN
17,18,Rachel Martinez,South,Corporate,Negotiation,18-02-2026,Bookshelf,Furniture,India,14000.0,9000,0.36,Target,Medium,Closed Won,Retail,25-02-2026
18,19,Sam Robinson,East,SMB,Qualified,20-02-2026,Webcam,Electronics,India,NaN,4200,0.40,Below Target,Low,Closed Lost,Online,27-02-2026
19,20,Tina Clark,West,consumer,Prospecting,22-02-2026,Desk Lamp,Furniture,India,5500.0,3000,0.45,Target,Low,Open,Retail,NaN
20,21,Uma Rodriguez,North,Corporate,Qualified,25-02-2026,Laptop,Electronics,India,62000.0,48000,0.23,Target,High,Closed Won,Online,03-03-2026
21,22,Victor Lewis,South,SMB,Proposal,28-02-2026,Office Chair,Furniture,India,20000.0,13500,0.33,Target,Medium,Open,Retail,NaN
22,23,Wendy Lee,East,Consumer,Negotiation,02-03-2026,Mobile Phone,Electronics,India,35000.0,24000,0.31,Target,High,Closed Won,Online,09-03-2026
23,24,xavier walker,West,Corporate,prospecting,05-03-2026,Printer,Electronics,India,13000.0,8000,0.38,Below Target,Low,Open,Retail,NaN
24,25,Yara Hall,North,SMB,Qualified,08-03-2026,Monitor,Electronics,India,17000.0,10000,0.41,Target,Medium,Closed Won,Online,15-03-2026
25,26,Zach Allen,South,Consumer,Proposal,10-03-2026,Dining Table,Furniture,India,38000.0,25000,0.34,Target,Medium,Open,Retail,NaN
26,27,alice johnson,north,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026
27,28,Ben Young,East,Corporate,Negotiation,15-03-2026,Projector,electronics,India,27000.0,16000,0.41,Below Target,Low,Closed Lost,Online,22-03-2026
28,29,Chloe King,West,SMB,Qualified,18-03-2026,Keyboard,Electronics,India,5000.0,2800,0.44,Target,Low,Open,Online,NaN
29,30,Daniel Wright,North,Corporate,Proposal,20-03-2026,sofa,Furniture,India,48000.0,32000,0.33,Target,High,Closed Won,Retail,28-03-2026
30,31,Eva Lopez,South,Consumer,Negotiation,22-03-2026,Tablet,Electronics,India,30000.0,20500,0.32,Target,Medium,Closed Won,Online,30-03-2026
31,32,Finn Hill,East,SMB,Prospecting,25-03-2026,Mouse,Electronics,India,2800.0,1300,0.54,Below Target,Low,Open,Online,NaN
32,33,Gina Scott,West,Corporate,Qualified,28-03-2026,Cabinet,Furniture,India,32000.0,22000,0.31,Target,Medium,Closed Won,Retail,05-04-2026
33,34,Harry Green,North,Consumer,Proposal,30-03-2026,Camera,ELECTRONICS,India,42000.0,29000,0.31,Target,High,Open,Online,NaN
34,35,Isla Adams,South,Corporate,Negotiation,02-04-2026,Conference Table,Furniture,India,68000.0,46000,0.32,Target,High,Closed Won,Retail,10-04-2026
35,36,Jon Baker,East,SMB,Qualified,05-04-2026,Headphones,Electronics,India,9000.0,5200,0.42,Below Target,Low,Closed Lost,Online,12-04-2026
36,37,Kara Nelson,West,Consumer,Prospecting,08-04-2026,Desk,Furniture,India,24000.0,16000,0.33,Target,Medium,Open,Retail,NaN
37,38,Leo Carter,North,Corporate,Qualified,10-04-2026,Smart Watch,Electronics,India,13500.0,7600,0.44,Target,Medium,Closed Won,Online,18-04-2026
38,39,Maya Mitchell,South,SMB,Proposal,12-04-2026,Bookshelf,Furniture,India,15500.0,9800,0.37,Target,Medium,Open,Retail,NaN
39,40,Nate Perez,East,Consumer,Negotiation,15-04-2026,Webcam,Electronics,India,7500.0,4500,0.40,Below Target,Low,Closed Lost,Online,22-04-2026
40,41,Owen Roberts,West,Corporate,Qualified,18-04-2026,Laptop,Electronics,India,60000.0,45500,0.24,Target,High,Closed Won,Online,26-04-2026
41,42,Paula Turner,north,SMB,Prospecting,20-04-2026,Office Chair,Furniture,India,19000.0,12500,0.34,Target,Medium,Open,Retail,NaN
42,43,Reed Phillips,South,Consumer,Proposal,22-04-2026,Mobile Phone,Electronics,India,33000.0,23000,0.30,Target,High,Closed Won,Online,30-04-2026
43,44,Sara Campbell,East,Corporate,Negotiation,not available,Printer,Electronics,India,14000.0,8500,0.39,Below Target,Low,Closed Lost,Retail,02-05-2026
44,45,Tom Parker,West,SMB,Qualified,28-04-2026,Monitor,Electronics,India,16000.0,9500,0.41,Target,Medium,Closed Won,Online,05-05-2026
45,46,Usha Evans,North,Consumer,Prospecting,01-05-2026,Dining Table,Furniture,India,40000.0,27000,0.33,Target,Medium,Open,Retail,NaN
46,47,Vikram Edwards,South,Corporate,Qualified,03-05-2026,Projector,Electronics,India,29000.0,17000,0.41,Target,High,Closed Won,online,10-05-2026
47,48,Willa Collins,East,SMB,Proposal,05-05-2026,Keyboard,Electronics,India,5200.0,3000,NaN,Below Target,Low,Open,Online,NaN
48,49,Yusuf Stewart,West,Consumer,Negotiation,08-05-2026,Sofa,Furniture,India,50000.0,34000,0.32,Target,High,Closed Won,Retail,15-05-2026
49,50,Zoe Sanchez,North,Corporate,Qualified,10-05-2026,Cabinet,Furniture,India,34000.0,23000,0.32,Target,Medium,Closed Won,Retail,18-05-2026

In [12]:
#add new column

data["Age"] = 40
data

,Customer ID,Customer Name,Region,Customer Segment,Sales Stage,Sales Date,Product,Category,Country,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date,Age
0,1,alice johnson,NORTH,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,40
1,2,BOB SMITH,South,Corporate,Qualified,08-01-2026,Office Chair,Furniture,India,18000.0,12000,0.33,Target,Medium,Closed Won,Retail,15-01-2026,40
2,3,Carol Davis,east,consumer,Negotiation,10-01-2026,Mobile Phone,electronics,India,32000.0,35000,-0.09,Below Target,Low,Closed Lost,Online,NaN,40
3,4,david lee,West,Corporate,Proposal,12-01-2026,Desk,Furniture,India,22000.0,15000,0.32,Target,Medium,Open,Retail,20-01-2026,40
4,5,EMILY BROWN,North,SMB,Prospecting,15-01-2026,Monitor,Electronics,India,15000.0,9000,0.40,Target,High,Open,Online,NaN,40
5,6,Frank Wilson,south,Consumer,Qualified,18-01-2026,Printer,electronics,India,12500.0,8000,0.36,Target,Medium,Closed Won,Retail,25-01-2026,40
6,7,grace miller,EAST,corporate,Negotiation,20-01-2026,Laptop,Electronics,India,58000.0,47000,0.19,Target,High,Closed Won,Online,28-01-2026,40
7,8,Henry Moore,west,SMB,Proposal,22-01-2026,Table,Furniture,India,26000.0,18000,0.31,Target,Medium,Open,Retail,NaN,40
8,9,Irene Taylor,NaN,consumer,Qualified,25-01-2026,Headphones,Electronics,India,8000.0,5000,0.38,Below Target,Low,Closed Lost,Online,02-02-2026,40
9,10,jack anderson,South,Corporate,Negotiation,28-01-2026,Sofa,Furniture,India,45000.0,30000,0.33,Target,High,Closed Won,Retail,05-02-2026,40
10,11,Karen Thomas,east,smb,Prospecting,01-02-2026,Keyboard,electronics,India,4500.0,2500,0.44,Target,Medium,Open,Online,NaN,40
11,12,Liam Jackson,West,Consumer,Qualified,03-02-2026,Tablet,Electronics,India,28000.0,19000,0.32,Target,High,Closed Won,Retail,10-02-2026,40
12,13,Mia White,North,Corporate,Proposal,05-02-2026,Cabinet,Furniture,India,30000.0,21000,0.30,Target,Medium,Open,Retail,NaN,40
13,14,NOAH HARRIS,South,consumer,Negotiation,08-02-2026,Smart Watch,Electronics,India,12000.0,7000,0.42,Below Target,Low,Closed Lost,Online,15-02-2026,40
14,15,Olivia Martin,East,SMB,Prospecting,10-02-2026,Mouse,Electronics,India,2500.0,1200,0.52,Target,Low,Open,Online,NaN,40
15,16,Peter Thompson,West,Corporate,Qualified,12-02-2026,Conference Table,Furniture,India,65000.0,45000,0.31,Target,High,Closed Won,Retail,20-02-2026,40
16,17,Quinn Garcia,North,Consumer,Proposal,15-02-2026,Camera,Electronics,India,40000.0,28000,0.30,Target,Medium,Open,Online,NaN,40
17,18,Rachel Martinez,South,Corporate,Negotiation,18-02-2026,Bookshelf,Furniture,India,14000.0,9000,0.36,Target,Medium,Closed Won,Retail,25-02-2026,40
18,19,Sam Robinson,East,SMB,Qualified,20-02-2026,Webcam,Electronics,India,NaN,4200,0.40,Below Target,Low,Closed Lost,Online,27-02-2026,40
19,20,Tina Clark,West,consumer,Prospecting,22-02-2026,Desk Lamp,Furniture,India,5500.0,3000,0.45,Target,Low,Open,Retail,NaN,40
20,21,Uma Rodriguez,North,Corporate,Qualified,25-02-2026,Laptop,Electronics,India,62000.0,48000,0.23,Target,High,Closed Won,Online,03-03-2026,40
21,22,Victor Lewis,South,SMB,Proposal,28-02-2026,Office Chair,Furniture,India,20000.0,13500,0.33,Target,Medium,Open,Retail,NaN,40
22,23,Wendy Lee,East,Consumer,Negotiation,02-03-2026,Mobile Phone,Electronics,India,35000.0,24000,0.31,Target,High,Closed Won,Online,09-03-2026,40
23,24,xavier walker,West,Corporate,prospecting,05-03-2026,Printer,Electronics,India,13000.0,8000,0.38,Below Target,Low,Open,Retail,NaN,40
24,25,Yara Hall,North,SMB,Qualified,08-03-2026,Monitor,Electronics,India,17000.0,10000,0.41,Target,Medium,Closed Won,Online,15-03-2026,40
25,26,Zach Allen,South,Consumer,Proposal,10-03-2026,Dining Table,Furniture,India,38000.0,25000,0.34,Target,Medium,Open,Retail,NaN,40
26,27,alice johnson,north,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,40
27,28,Ben Young,East,Corporate,Negotiation,15-03-2026,Projector,electronics,India,27000.0,16000,0.41,Below Target,Low,Closed Lost,Online,22-03-2026,40
28,29,Chloe King,West,SMB,Qualified,18-03-2026,Keyboard,Electronics,India,5000.0,2800,0.44,Target,Low,Open,Online,NaN,40
29,30,Daniel Wright,North,Corporate,Proposal,20-03-2026,sofa,Furniture,India,48000.0,32000,0.33,Target,High,Closed Won,Retail,28-03-2026,40
30,31,Eva Lopez,South,Consumer,Negotiation,22-03-2026,Tablet,Electronics,India,30000.0,20500,0.32,Target,Medium,Closed Won,Online,30-03-2026,40
31,32,Finn Hill,East,SMB,Prospecting,25-03-2026,Mouse,Electronics,India,2800.0,1300,0.54,Below Target,Low,Open,Online,NaN,40
32,33,Gina Scott,West,Corporate,Qualified,28-03-2026,Cabinet,Furniture,India,32000.0,22000,0.31,Target,Medium,Closed Won,Retail,05-04-2026,40
33,34,Harry Green,North,Consumer,Proposal,30-03-2026,Camera,ELECTRONICS,India,42000.0,29000,0.31,Target,High,Open,Online,NaN,40
34,35,Isla Adams,South,Corporate,Negotiation,02-04-2026,Conference Table,Furniture,India,68000.0,46000,0.32,Target,High,Closed Won,Retail,10-04-2026,40
35,36,Jon Baker,East,SMB,Qualified,05-04-2026,Headphones,Electronics,India,9000.0,5200,0.42,Below Target,Low,Closed Lost,Online,12-04-2026,40
36,37,Kara Nelson,West,Consumer,Prospecting,08-04-2026,Desk,Furniture,India,24000.0,16000,0.33,Target,Medium,Open,Retail,NaN,40
37,38,Leo Carter,North,Corporate,Qualified,10-04-2026,Smart Watch,Electronics,India,13500.0,7600,0.44,Target,Medium,Closed Won,Online,18-04-2026,40
38,39,Maya Mitchell,South,SMB,Proposal,12-04-2026,Bookshelf,Furniture,India,15500.0,9800,0.37,Target,Medium,Open,Retail,NaN,40
39,40,Nate Perez,East,Consumer,Negotiation,15-04-2026,Webcam,Electronics,India,7500.0,4500,0.40,Below Target,Low,Closed Lost,Online,22-04-2026,40
40,41,Owen Roberts,West,Corporate,Qualified,18-04-2026,Laptop,Electronics,India,60000.0,45500,0.24,Target,High,Closed Won,Online,26-04-2026,40
41,42,Paula Turner,north,SMB,Prospecting,20-04-2026,Office Chair,Furniture,India,19000.0,12500,0.34,Target,Medium,Open,Retail,NaN,40
42,43,Reed Phillips,South,Consumer,Proposal,22-04-2026,Mobile Phone,Electronics,India,33000.0,23000,0.30,Target,High,Closed Won,Online,30-04-2026,40
43,44,Sara Campbell,East,Corporate,Negotiation,not available,Printer,Electronics,India,14000.0,8500,0.39,Below Target,Low,Closed Lost,Retail,02-05-2026,40
44,45,Tom Parker,West,SMB,Qualified,28-04-2026,Monitor,Electronics,India,16000.0,9500,0.41,Target,Medium,Closed Won,Online,05-05-2026,40
45,46,Usha Evans,North,Consumer,Prospecting,01-05-2026,Dining Table,Furniture,India,40000.0,27000,0.33,Target,Medium,Open,Retail,NaN,40
46,47,Vikram Edwards,South,Corporate,Qualified,03-05-2026,Projector,Electronics,India,29000.0,17000,0.41,Target,High,Closed Won,online,10-05-2026,40
47,48,Willa Collins,East,SMB,Proposal,05-05-2026,Keyboard,Electronics,India,5200.0,3000,NaN,Below Target,Low,Open,Online,NaN,40
48,49,Yusuf Stewart,West,Consumer,Negotiation,08-05-2026,Sofa,Furniture,India,50000.0,34000,0.32,Target,High,Closed Won,Retail,15-05-2026,40
49,50,Zoe Sanchez,North,Corporate,Qualified,10-05-2026,Cabinet,Furniture,India,34000.0,23000,0.32,Target,Medium,Closed Won,Retail,18-05-2026,40

In [14]:
data['difference'] = data['Sales'] > 15000
data

,Customer ID,Customer Name,Region,Customer Segment,Sales Stage,Sales Date,Product,Category,Country,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date,Age,difference
0,1,alice johnson,NORTH,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,40,True
1,2,BOB SMITH,South,Corporate,Qualified,08-01-2026,Office Chair,Furniture,India,18000.0,12000,0.33,Target,Medium,Closed Won,Retail,15-01-2026,40,True
2,3,Carol Davis,east,consumer,Negotiation,10-01-2026,Mobile Phone,electronics,India,32000.0,35000,-0.09,Below Target,Low,Closed Lost,Online,NaN,40,True
3,4,david lee,West,Corporate,Proposal,12-01-2026,Desk,Furniture,India,22000.0,15000,0.32,Target,Medium,Open,Retail,20-01-2026,40,True
4,5,EMILY BROWN,North,SMB,Prospecting,15-01-2026,Monitor,Electronics,India,15000.0,9000,0.40,Target,High,Open,Online,NaN,40,False
5,6,Frank Wilson,south,Consumer,Qualified,18-01-2026,Printer,electronics,India,12500.0,8000,0.36,Target,Medium,Closed Won,Retail,25-01-2026,40,False
6,7,grace miller,EAST,corporate,Negotiation,20-01-2026,Laptop,Electronics,India,58000.0,47000,0.19,Target,High,Closed Won,Online,28-01-2026,40,True
7,8,Henry Moore,west,SMB,Proposal,22-01-2026,Table,Furniture,India,26000.0,18000,0.31,Target,Medium,Open,Retail,NaN,40,True
8,9,Irene Taylor,NaN,consumer,Qualified,25-01-2026,Headphones,Electronics,India,8000.0,5000,0.38,Below Target,Low,Closed Lost,Online,02-02-2026,40,False
9,10,jack anderson,South,Corporate,Negotiation,28-01-2026,Sofa,Furniture,India,45000.0,30000,0.33,Target,High,Closed Won,Retail,05-02-2026,40,True
10,11,Karen Thomas,east,smb,Prospecting,01-02-2026,Keyboard,electronics,India,4500.0,2500,0.44,Target,Medium,Open,Online,NaN,40,False
11,12,Liam Jackson,West,Consumer,Qualified,03-02-2026,Tablet,Electronics,India,28000.0,19000,0.32,Target,High,Closed Won,Retail,10-02-2026,40,True
12,13,Mia White,North,Corporate,Proposal,05-02-2026,Cabinet,Furniture,India,30000.0,21000,0.30,Target,Medium,Open,Retail,NaN,40,True
13,14,NOAH HARRIS,South,consumer,Negotiation,08-02-2026,Smart Watch,Electronics,India,12000.0,7000,0.42,Below Target,Low,Closed Lost,Online,15-02-2026,40,False
14,15,Olivia Martin,East,SMB,Prospecting,10-02-2026,Mouse,Electronics,India,2500.0,1200,0.52,Target,Low,Open,Online,NaN,40,False
15,16,Peter Thompson,West,Corporate,Qualified,12-02-2026,Conference Table,Furniture,India,65000.0,45000,0.31,Target,High,Closed Won,Retail,20-02-2026,40,True
16,17,Quinn Garcia,North,Consumer,Proposal,15-02-2026,Camera,Electronics,India,40000.0,28000,0.30,Target,Medium,Open,Online,NaN,40,True
17,18,Rachel Martinez,South,Corporate,Negotiation,18-02-2026,Bookshelf,Furniture,India,14000.0,9000,0.36,Target,Medium,Closed Won,Retail,25-02-2026,40,False
18,19,Sam Robinson,East,SMB,Qualified,20-02-2026,Webcam,Electronics,India,NaN,4200,0.40,Below Target,Low,Closed Lost,Online,27-02-2026,40,False
19,20,Tina Clark,West,consumer,Prospecting,22-02-2026,Desk Lamp,Furniture,India,5500.0,3000,0.45,Target,Low,Open,Retail,NaN,40,False
20,21,Uma Rodriguez,North,Corporate,Qualified,25-02-2026,Laptop,Electronics,India,62000.0,48000,0.23,Target,High,Closed Won,Online,03-03-2026,40,True
21,22,Victor Lewis,South,SMB,Proposal,28-02-2026,Office Chair,Furniture,India,20000.0,13500,0.33,Target,Medium,Open,Retail,NaN,40,True
22,23,Wendy Lee,East,Consumer,Negotiation,02-03-2026,Mobile Phone,Electronics,India,35000.0,24000,0.31,Target,High,Closed Won,Online,09-03-2026,40,True
23,24,xavier walker,West,Corporate,prospecting,05-03-2026,Printer,Electronics,India,13000.0,8000,0.38,Below Target,Low,Open,Retail,NaN,40,False
24,25,Yara Hall,North,SMB,Qualified,08-03-2026,Monitor,Electronics,India,17000.0,10000,0.41,Target,Medium,Closed Won,Online,15-03-2026,40,True
25,26,Zach Allen,South,Consumer,Proposal,10-03-2026,Dining Table,Furniture,India,38000.0,25000,0.34,Target,Medium,Open,Retail,NaN,40,True
26,27,alice johnson,north,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,40,True
27,28,Ben Young,East,Corporate,Negotiation,15-03-2026,Projector,electronics,India,27000.0,16000,0.41,Below Target,Low,Closed Lost,Online,22-03-2026,40,True
28,29,Chloe King,West,SMB,Qualified,18-03-2026,Keyboard,Electronics,India,5000.0,2800,0.44,Target,Low,Open,Online,NaN,40,False
29,30,Daniel Wright,North,Corporate,Proposal,20-03-2026,sofa,Furniture,India,48000.0,32000,0.33,Target,High,Closed Won,Retail,28-03-2026,40,True
30,31,Eva Lopez,South,Consumer,Negotiation,22-03-2026,Tablet,Electronics,India,30000.0,20500,0.32,Target,Medium,Closed Won,Online,30-03-2026,40,True
31,32,Finn Hill,East,SMB,Prospecting,25-03-2026,Mouse,Electronics,India,2800.0,1300,0.54,Below Target,Low,Open,Online,NaN,40,False
32,33,Gina Scott,West,Corporate,Qualified,28-03-2026,Cabinet,Furniture,India,32000.0,22000,0.31,Target,Medium,Closed Won,Retail,05-04-2026,40,True
33,34,Harry Green,North,Consumer,Proposal,30-03-2026,Camera,ELECTRONICS,India,42000.0,29000,0.31,Target,High,Open,Online,NaN,40,True
34,35,Isla Adams,South,Corporate,Negotiation,02-04-2026,Conference Table,Furniture,India,68000.0,46000,0.32,Target,High,Closed Won,Retail,10-04-2026,40,True
35,36,Jon Baker,East,SMB,Qualified,05-04-2026,Headphones,Electronics,India,9000.0,5200,0.42,Below Target,Low,Closed Lost,Online,12-04-2026,40,False
36,37,Kara Nelson,West,Consumer,Prospecting,08-04-2026,Desk,Furniture,India,24000.0,16000,0.33,Target,Medium,Open,Retail,NaN,40,True
37,38,Leo Carter,North,Corporate,Qualified,10-04-2026,Smart Watch,Electronics,India,13500.0,7600,0.44,Target,Medium,Closed Won,Online,18-04-2026,40,False
38,39,Maya Mitchell,South,SMB,Proposal,12-04-2026,Bookshelf,Furniture,India,15500.0,9800,0.37,Target,Medium,Open,Retail,NaN,40,True
39,40,Nate Perez,East,Consumer,Negotiation,15-04-2026,Webcam,Electronics,India,7500.0,4500,0.40,Below Target,Low,Closed Lost,Online,22-04-2026,40,False
40,41,Owen Roberts,West,Corporate,Qualified,18-04-2026,Laptop,Electronics,India,60000.0,45500,0.24,Target,High,Closed Won,Online,26-04-2026,40,True
41,42,Paula Turner,north,SMB,Prospecting,20-04-2026,Office Chair,Furniture,India,19000.0,12500,0.34,Target,Medium,Open,Retail,NaN,40,True
42,43,Reed Phillips,South,Consumer,Proposal,22-04-2026,Mobile Phone,Electronics,India,33000.0,23000,0.30,Target,High,Closed Won,Online,30-04-2026,40,True
43,44,Sara Campbell,East,Corporate,Negotiation,not available,Printer,Electronics,India,14000.0,8500,0.39,Below Target,Low,Closed Lost,Retail,02-05-2026,40,False
44,45,Tom Parker,West,SMB,Qualified,28-04-2026,Monitor,Electronics,India,16000.0,9500,0.41,Target,Medium,Closed Won,Online,05-05-2026,40,True
45,46,Usha Evans,North,Consumer,Prospecting,01-05-2026,Dining Table,Furniture,India,40000.0,27000,0.33,Target,Medium,Open,Retail,NaN,40,True
46,47,Vikram Edwards,South,Corporate,Qualified,03-05-2026,Projector,Electronics,India,29000.0,17000,0.41,Target,High,Closed Won,online,10-05-2026,40,True
47,48,Willa Collins,East,SMB,Proposal,05-05-2026,Keyboard,Electronics,India,5200.0,3000,NaN,Below Target,Low,Open,Online,NaN,40,False
48,49,Yusuf Stewart,West,Consumer,Negotiation,08-05-2026,Sofa,Furniture,India,50000.0,34000,0.32,Target,High,Closed Won,Retail,15-05-2026,40,True
49,50,Zoe Sanchez,North,Corporate,Qualified,10-05-2026,Cabinet,Furniture,India,34000.0,23000,0.32,Target,Medium,Closed Won,Retail,18-05-2026,40,True

In [16]:
#update

data.loc[0,"Age"] = 50
data

,Customer ID,Customer Name,Region,Customer Segment,Sales Stage,Sales Date,Product,Category,Country,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date,Age,difference
0,1,alice johnson,NORTH,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,50,True
1,2,BOB SMITH,South,Corporate,Qualified,08-01-2026,Office Chair,Furniture,India,18000.0,12000,0.33,Target,Medium,Closed Won,Retail,15-01-2026,40,True
2,3,Carol Davis,east,consumer,Negotiation,10-01-2026,Mobile Phone,electronics,India,32000.0,35000,-0.09,Below Target,Low,Closed Lost,Online,NaN,40,True
3,4,david lee,West,Corporate,Proposal,12-01-2026,Desk,Furniture,India,22000.0,15000,0.32,Target,Medium,Open,Retail,20-01-2026,40,True
4,5,EMILY BROWN,North,SMB,Prospecting,15-01-2026,Monitor,Electronics,India,15000.0,9000,0.40,Target,High,Open,Online,NaN,40,False
5,6,Frank Wilson,south,Consumer,Qualified,18-01-2026,Printer,electronics,India,12500.0,8000,0.36,Target,Medium,Closed Won,Retail,25-01-2026,40,False
6,7,grace miller,EAST,corporate,Negotiation,20-01-2026,Laptop,Electronics,India,58000.0,47000,0.19,Target,High,Closed Won,Online,28-01-2026,40,True
7,8,Henry Moore,west,SMB,Proposal,22-01-2026,Table,Furniture,India,26000.0,18000,0.31,Target,Medium,Open,Retail,NaN,40,True
8,9,Irene Taylor,NaN,consumer,Qualified,25-01-2026,Headphones,Electronics,India,8000.0,5000,0.38,Below Target,Low,Closed Lost,Online,02-02-2026,40,False
9,10,jack anderson,South,Corporate,Negotiation,28-01-2026,Sofa,Furniture,India,45000.0,30000,0.33,Target,High,Closed Won,Retail,05-02-2026,40,True
10,11,Karen Thomas,east,smb,Prospecting,01-02-2026,Keyboard,electronics,India,4500.0,2500,0.44,Target,Medium,Open,Online,NaN,40,False
11,12,Liam Jackson,West,Consumer,Qualified,03-02-2026,Tablet,Electronics,India,28000.0,19000,0.32,Target,High,Closed Won,Retail,10-02-2026,40,True
12,13,Mia White,North,Corporate,Proposal,05-02-2026,Cabinet,Furniture,India,30000.0,21000,0.30,Target,Medium,Open,Retail,NaN,40,True
13,14,NOAH HARRIS,South,consumer,Negotiation,08-02-2026,Smart Watch,Electronics,India,12000.0,7000,0.42,Below Target,Low,Closed Lost,Online,15-02-2026,40,False
14,15,Olivia Martin,East,SMB,Prospecting,10-02-2026,Mouse,Electronics,India,2500.0,1200,0.52,Target,Low,Open,Online,NaN,40,False
15,16,Peter Thompson,West,Corporate,Qualified,12-02-2026,Conference Table,Furniture,India,65000.0,45000,0.31,Target,High,Closed Won,Retail,20-02-2026,40,True
16,17,Quinn Garcia,North,Consumer,Proposal,15-02-2026,Camera,Electronics,India,40000.0,28000,0.30,Target,Medium,Open,Online,NaN,40,True
17,18,Rachel Martinez,South,Corporate,Negotiation,18-02-2026,Bookshelf,Furniture,India,14000.0,9000,0.36,Target,Medium,Closed Won,Retail,25-02-2026,40,False
18,19,Sam Robinson,East,SMB,Qualified,20-02-2026,Webcam,Electronics,India,NaN,4200,0.40,Below Target,Low,Closed Lost,Online,27-02-2026,40,False
19,20,Tina Clark,West,consumer,Prospecting,22-02-2026,Desk Lamp,Furniture,India,5500.0,3000,0.45,Target,Low,Open,Retail,NaN,40,False
20,21,Uma Rodriguez,North,Corporate,Qualified,25-02-2026,Laptop,Electronics,India,62000.0,48000,0.23,Target,High,Closed Won,Online,03-03-2026,40,True
21,22,Victor Lewis,South,SMB,Proposal,28-02-2026,Office Chair,Furniture,India,20000.0,13500,0.33,Target,Medium,Open,Retail,NaN,40,True
22,23,Wendy Lee,East,Consumer,Negotiation,02-03-2026,Mobile Phone,Electronics,India,35000.0,24000,0.31,Target,High,Closed Won,Online,09-03-2026,40,True
23,24,xavier walker,West,Corporate,prospecting,05-03-2026,Printer,Electronics,India,13000.0,8000,0.38,Below Target,Low,Open,Retail,NaN,40,False
24,25,Yara Hall,North,SMB,Qualified,08-03-2026,Monitor,Electronics,India,17000.0,10000,0.41,Target,Medium,Closed Won,Online,15-03-2026,40,True
25,26,Zach Allen,South,Consumer,Proposal,10-03-2026,Dining Table,Furniture,India,38000.0,25000,0.34,Target,Medium,Open,Retail,NaN,40,True
26,27,alice johnson,north,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,40,True
27,28,Ben Young,East,Corporate,Negotiation,15-03-2026,Projector,electronics,India,27000.0,16000,0.41,Below Target,Low,Closed Lost,Online,22-03-2026,40,True
28,29,Chloe King,West,SMB,Qualified,18-03-2026,Keyboard,Electronics,India,5000.0,2800,0.44,Target,Low,Open,Online,NaN,40,False
29,30,Daniel Wright,North,Corporate,Proposal,20-03-2026,sofa,Furniture,India,48000.0,32000,0.33,Target,High,Closed Won,Retail,28-03-2026,40,True
30,31,Eva Lopez,South,Consumer,Negotiation,22-03-2026,Tablet,Electronics,India,30000.0,20500,0.32,Target,Medium,Closed Won,Online,30-03-2026,40,True
31,32,Finn Hill,East,SMB,Prospecting,25-03-2026,Mouse,Electronics,India,2800.0,1300,0.54,Below Target,Low,Open,Online,NaN,40,False
32,33,Gina Scott,West,Corporate,Qualified,28-03-2026,Cabinet,Furniture,India,32000.0,22000,0.31,Target,Medium,Closed Won,Retail,05-04-2026,40,True
33,34,Harry Green,North,Consumer,Proposal,30-03-2026,Camera,ELECTRONICS,India,42000.0,29000,0.31,Target,High,Open,Online,NaN,40,True
34,35,Isla Adams,South,Corporate,Negotiation,02-04-2026,Conference Table,Furniture,India,68000.0,46000,0.32,Target,High,Closed Won,Retail,10-04-2026,40,True
35,36,Jon Baker,East,SMB,Qualified,05-04-2026,Headphones,Electronics,India,9000.0,5200,0.42,Below Target,Low,Closed Lost,Online,12-04-2026,40,False
36,37,Kara Nelson,West,Consumer,Prospecting,08-04-2026,Desk,Furniture,India,24000.0,16000,0.33,Target,Medium,Open,Retail,NaN,40,True
37,38,Leo Carter,North,Corporate,Qualified,10-04-2026,Smart Watch,Electronics,India,13500.0,7600,0.44,Target,Medium,Closed Won,Online,18-04-2026,40,False
38,39,Maya Mitchell,South,SMB,Proposal,12-04-2026,Bookshelf,Furniture,India,15500.0,9800,0.37,Target,Medium,Open,Retail,NaN,40,True
39,40,Nate Perez,East,Consumer,Negotiation,15-04-2026,Webcam,Electronics,India,7500.0,4500,0.40,Below Target,Low,Closed Lost,Online,22-04-2026,40,False
40,41,Owen Roberts,West,Corporate,Qualified,18-04-2026,Laptop,Electronics,India,60000.0,45500,0.24,Target,High,Closed Won,Online,26-04-2026,40,True
41,42,Paula Turner,north,SMB,Prospecting,20-04-2026,Office Chair,Furniture,India,19000.0,12500,0.34,Target,Medium,Open,Retail,NaN,40,True
42,43,Reed Phillips,South,Consumer,Proposal,22-04-2026,Mobile Phone,Electronics,India,33000.0,23000,0.30,Target,High,Closed Won,Online,30-04-2026,40,True
43,44,Sara Campbell,East,Corporate,Negotiation,not available,Printer,Electronics,India,14000.0,8500,0.39,Below Target,Low,Closed Lost,Retail,02-05-2026,40,False
44,45,Tom Parker,West,SMB,Qualified,28-04-2026,Monitor,Electronics,India,16000.0,9500,0.41,Target,Medium,Closed Won,Online,05-05-2026,40,True
45,46,Usha Evans,North,Consumer,Prospecting,01-05-2026,Dining Table,Furniture,India,40000.0,27000,0.33,Target,Medium,Open,Retail,NaN,40,True
46,47,Vikram Edwards,South,Corporate,Qualified,03-05-2026,Projector,Electronics,India,29000.0,17000,0.41,Target,High,Closed Won,online,10-05-2026,40,True
47,48,Willa Collins,East,SMB,Proposal,05-05-2026,Keyboard,Electronics,India,5200.0,3000,NaN,Below Target,Low,Open,Online,NaN,40,False
48,49,Yusuf Stewart,West,Consumer,Negotiation,08-05-2026,Sofa,Furniture,India,50000.0,34000,0.32,Target,High,Closed Won,Retail,15-05-2026,40,True
49,50,Zoe Sanchez,North,Corporate,Qualified,10-05-2026,Cabinet,Furniture,India,34000.0,23000,0.32,Target,Medium,Closed Won,Retail,18-05-2026,40,True

In [17]:
#deleting column

data.drop("Age", axis = 1)

,Customer ID,Customer Name,Region,Customer Segment,Sales Stage,Sales Date,Product,Category,Country,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date,difference
0,1,alice johnson,NORTH,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,True
1,2,BOB SMITH,South,Corporate,Qualified,08-01-2026,Office Chair,Furniture,India,18000.0,12000,0.33,Target,Medium,Closed Won,Retail,15-01-2026,True
2,3,Carol Davis,east,consumer,Negotiation,10-01-2026,Mobile Phone,electronics,India,32000.0,35000,-0.09,Below Target,Low,Closed Lost,Online,NaN,True
3,4,david lee,West,Corporate,Proposal,12-01-2026,Desk,Furniture,India,22000.0,15000,0.32,Target,Medium,Open,Retail,20-01-2026,True
4,5,EMILY BROWN,North,SMB,Prospecting,15-01-2026,Monitor,Electronics,India,15000.0,9000,0.40,Target,High,Open,Online,NaN,False
5,6,Frank Wilson,south,Consumer,Qualified,18-01-2026,Printer,electronics,India,12500.0,8000,0.36,Target,Medium,Closed Won,Retail,25-01-2026,False
6,7,grace miller,EAST,corporate,Negotiation,20-01-2026,Laptop,Electronics,India,58000.0,47000,0.19,Target,High,Closed Won,Online,28-01-2026,True
7,8,Henry Moore,west,SMB,Proposal,22-01-2026,Table,Furniture,India,26000.0,18000,0.31,Target,Medium,Open,Retail,NaN,True
8,9,Irene Taylor,NaN,consumer,Qualified,25-01-2026,Headphones,Electronics,India,8000.0,5000,0.38,Below Target,Low,Closed Lost,Online,02-02-2026,False
9,10,jack anderson,South,Corporate,Negotiation,28-01-2026,Sofa,Furniture,India,45000.0,30000,0.33,Target,High,Closed Won,Retail,05-02-2026,True
10,11,Karen Thomas,east,smb,Prospecting,01-02-2026,Keyboard,electronics,India,4500.0,2500,0.44,Target,Medium,Open,Online,NaN,False
11,12,Liam Jackson,West,Consumer,Qualified,03-02-2026,Tablet,Electronics,India,28000.0,19000,0.32,Target,High,Closed Won,Retail,10-02-2026,True
12,13,Mia White,North,Corporate,Proposal,05-02-2026,Cabinet,Furniture,India,30000.0,21000,0.30,Target,Medium,Open,Retail,NaN,True
13,14,NOAH HARRIS,South,consumer,Negotiation,08-02-2026,Smart Watch,Electronics,India,12000.0,7000,0.42,Below Target,Low,Closed Lost,Online,15-02-2026,False
14,15,Olivia Martin,East,SMB,Prospecting,10-02-2026,Mouse,Electronics,India,2500.0,1200,0.52,Target,Low,Open,Online,NaN,False
15,16,Peter Thompson,West,Corporate,Qualified,12-02-2026,Conference Table,Furniture,India,65000.0,45000,0.31,Target,High,Closed Won,Retail,20-02-2026,True
16,17,Quinn Garcia,North,Consumer,Proposal,15-02-2026,Camera,Electronics,India,40000.0,28000,0.30,Target,Medium,Open,Online,NaN,True
17,18,Rachel Martinez,South,Corporate,Negotiation,18-02-2026,Bookshelf,Furniture,India,14000.0,9000,0.36,Target,Medium,Closed Won,Retail,25-02-2026,False
18,19,Sam Robinson,East,SMB,Qualified,20-02-2026,Webcam,Electronics,India,NaN,4200,0.40,Below Target,Low,Closed Lost,Online,27-02-2026,False
19,20,Tina Clark,West,consumer,Prospecting,22-02-2026,Desk Lamp,Furniture,India,5500.0,3000,0.45,Target,Low,Open,Retail,NaN,False
20,21,Uma Rodriguez,North,Corporate,Qualified,25-02-2026,Laptop,Electronics,India,62000.0,48000,0.23,Target,High,Closed Won,Online,03-03-2026,True
21,22,Victor Lewis,South,SMB,Proposal,28-02-2026,Office Chair,Furniture,India,20000.0,13500,0.33,Target,Medium,Open,Retail,NaN,True
22,23,Wendy Lee,East,Consumer,Negotiation,02-03-2026,Mobile Phone,Electronics,India,35000.0,24000,0.31,Target,High,Closed Won,Online,09-03-2026,True
23,24,xavier walker,West,Corporate,prospecting,05-03-2026,Printer,Electronics,India,13000.0,8000,0.38,Below Target,Low,Open,Retail,NaN,False
24,25,Yara Hall,North,SMB,Qualified,08-03-2026,Monitor,Electronics,India,17000.0,10000,0.41,Target,Medium,Closed Won,Online,15-03-2026,True
25,26,Zach Allen,South,Consumer,Proposal,10-03-2026,Dining Table,Furniture,India,38000.0,25000,0.34,Target,Medium,Open,Retail,NaN,True
26,27,alice johnson,north,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,True
27,28,Ben Young,East,Corporate,Negotiation,15-03-2026,Projector,electronics,India,27000.0,16000,0.41,Below Target,Low,Closed Lost,Online,22-03-2026,True
28,29,Chloe King,West,SMB,Qualified,18-03-2026,Keyboard,Electronics,India,5000.0,2800,0.44,Target,Low,Open,Online,NaN,False
29,30,Daniel Wright,North,Corporate,Proposal,20-03-2026,sofa,Furniture,India,48000.0,32000,0.33,Target,High,Closed Won,Retail,28-03-2026,True
30,31,Eva Lopez,South,Consumer,Negotiation,22-03-2026,Tablet,Electronics,India,30000.0,20500,0.32,Target,Medium,Closed Won,Online,30-03-2026,True
31,32,Finn Hill,East,SMB,Prospecting,25-03-2026,Mouse,Electronics,India,2800.0,1300,0.54,Below Target,Low,Open,Online,NaN,False
32,33,Gina Scott,West,Corporate,Qualified,28-03-2026,Cabinet,Furniture,India,32000.0,22000,0.31,Target,Medium,Closed Won,Retail,05-04-2026,True
33,34,Harry Green,North,Consumer,Proposal,30-03-2026,Camera,ELECTRONICS,India,42000.0,29000,0.31,Target,High,Open,Online,NaN,True
34,35,Isla Adams,South,Corporate,Negotiation,02-04-2026,Conference Table,Furniture,India,68000.0,46000,0.32,Target,High,Closed Won,Retail,10-04-2026,True
35,36,Jon Baker,East,SMB,Qualified,05-04-2026,Headphones,Electronics,India,9000.0,5200,0.42,Below Target,Low,Closed Lost,Online,12-04-2026,False
36,37,Kara Nelson,West,Consumer,Prospecting,08-04-2026,Desk,Furniture,India,24000.0,16000,0.33,Target,Medium,Open,Retail,NaN,True
37,38,Leo Carter,North,Corporate,Qualified,10-04-2026,Smart Watch,Electronics,India,13500.0,7600,0.44,Target,Medium,Closed Won,Online,18-04-2026,False
38,39,Maya Mitchell,South,SMB,Proposal,12-04-2026,Bookshelf,Furniture,India,15500.0,9800,0.37,Target,Medium,Open,Retail,NaN,True
39,40,Nate Perez,East,Consumer,Negotiation,15-04-2026,Webcam,Electronics,India,7500.0,4500,0.40,Below Target,Low,Closed Lost,Online,22-04-2026,False
40,41,Owen Roberts,West,Corporate,Qualified,18-04-2026,Laptop,Electronics,India,60000.0,45500,0.24,Target,High,Closed Won,Online,26-04-2026,True
41,42,Paula Turner,north,SMB,Prospecting,20-04-2026,Office Chair,Furniture,India,19000.0,12500,0.34,Target,Medium,Open,Retail,NaN,True
42,43,Reed Phillips,South,Consumer,Proposal,22-04-2026,Mobile Phone,Electronics,India,33000.0,23000,0.30,Target,High,Closed Won,Online,30-04-2026,True
43,44,Sara Campbell,East,Corporate,Negotiation,not available,Printer,Electronics,India,14000.0,8500,0.39,Below Target,Low,Closed Lost,Retail,02-05-2026,False
44,45,Tom Parker,West,SMB,Qualified,28-04-2026,Monitor,Electronics,India,16000.0,9500,0.41,Target,Medium,Closed Won,Online,05-05-2026,True
45,46,Usha Evans,North,Consumer,Prospecting,01-05-2026,Dining Table,Furniture,India,40000.0,27000,0.33,Target,Medium,Open,Retail,NaN,True
46,47,Vikram Edwards,South,Corporate,Qualified,03-05-2026,Projector,Electronics,India,29000.0,17000,0.41,Target,High,Closed Won,online,10-05-2026,True
47,48,Willa Collins,East,SMB,Proposal,05-05-2026,Keyboard,Electronics,India,5200.0,3000,NaN,Below Target,Low,Open,Online,NaN,False
48,49,Yusuf Stewart,West,Consumer,Negotiation,08-05-2026,Sofa,Furniture,India,50000.0,34000,0.32,Target,High,Closed Won,Retail,15-05-2026,True
49,50,Zoe Sanchez,North,Corporate,Qualified,10-05-2026,Cabinet,Furniture,India,34000.0,23000,0.32,Target,Medium,Closed Won,Retail,18-05-2026,True

In [18]:
data.drop(["Sales Date","Country"] ,axis = 1)

,Customer ID,Customer Name,Region,Customer Segment,Sales Stage,Product,Category,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date,Age,difference
0,1,alice johnson,NORTH,Consumer,Prospecting,Laptop,Electronics,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,50,True
1,2,BOB SMITH,South,Corporate,Qualified,Office Chair,Furniture,18000.0,12000,0.33,Target,Medium,Closed Won,Retail,15-01-2026,40,True
2,3,Carol Davis,east,consumer,Negotiation,Mobile Phone,electronics,32000.0,35000,-0.09,Below Target,Low,Closed Lost,Online,NaN,40,True
3,4,david lee,West,Corporate,Proposal,Desk,Furniture,22000.0,15000,0.32,Target,Medium,Open,Retail,20-01-2026,40,True
4,5,EMILY BROWN,North,SMB,Prospecting,Monitor,Electronics,15000.0,9000,0.40,Target,High,Open,Online,NaN,40,False
5,6,Frank Wilson,south,Consumer,Qualified,Printer,electronics,12500.0,8000,0.36,Target,Medium,Closed Won,Retail,25-01-2026,40,False
6,7,grace miller,EAST,corporate,Negotiation,Laptop,Electronics,58000.0,47000,0.19,Target,High,Closed Won,Online,28-01-2026,40,True
7,8,Henry Moore,west,SMB,Proposal,Table,Furniture,26000.0,18000,0.31,Target,Medium,Open,Retail,NaN,40,True
8,9,Irene Taylor,NaN,consumer,Qualified,Headphones,Electronics,8000.0,5000,0.38,Below Target,Low,Closed Lost,Online,02-02-2026,40,False
9,10,jack anderson,South,Corporate,Negotiation,Sofa,Furniture,45000.0,30000,0.33,Target,High,Closed Won,Retail,05-02-2026,40,True
10,11,Karen Thomas,east,smb,Prospecting,Keyboard,electronics,4500.0,2500,0.44,Target,Medium,Open,Online,NaN,40,False
11,12,Liam Jackson,West,Consumer,Qualified,Tablet,Electronics,28000.0,19000,0.32,Target,High,Closed Won,Retail,10-02-2026,40,True
12,13,Mia White,North,Corporate,Proposal,Cabinet,Furniture,30000.0,21000,0.30,Target,Medium,Open,Retail,NaN,40,True
13,14,NOAH HARRIS,South,consumer,Negotiation,Smart Watch,Electronics,12000.0,7000,0.42,Below Target,Low,Closed Lost,Online,15-02-2026,40,False
14,15,Olivia Martin,East,SMB,Prospecting,Mouse,Electronics,2500.0,1200,0.52,Target,Low,Open,Online,NaN,40,False
15,16,Peter Thompson,West,Corporate,Qualified,Conference Table,Furniture,65000.0,45000,0.31,Target,High,Closed Won,Retail,20-02-2026,40,True
16,17,Quinn Garcia,North,Consumer,Proposal,Camera,Electronics,40000.0,28000,0.30,Target,Medium,Open,Online,NaN,40,True
17,18,Rachel Martinez,South,Corporate,Negotiation,Bookshelf,Furniture,14000.0,9000,0.36,Target,Medium,Closed Won,Retail,25-02-2026,40,False
18,19,Sam Robinson,East,SMB,Qualified,Webcam,Electronics,NaN,4200,0.40,Below Target,Low,Closed Lost,Online,27-02-2026,40,False
19,20,Tina Clark,West,consumer,Prospecting,Desk Lamp,Furniture,5500.0,3000,0.45,Target,Low,Open,Retail,NaN,40,False
20,21,Uma Rodriguez,North,Corporate,Qualified,Laptop,Electronics,62000.0,48000,0.23,Target,High,Closed Won,Online,03-03-2026,40,True
21,22,Victor Lewis,South,SMB,Proposal,Office Chair,Furniture,20000.0,13500,0.33,Target,Medium,Open,Retail,NaN,40,True
22,23,Wendy Lee,East,Consumer,Negotiation,Mobile Phone,Electronics,35000.0,24000,0.31,Target,High,Closed Won,Online,09-03-2026,40,True
23,24,xavier walker,West,Corporate,prospecting,Printer,Electronics,13000.0,8000,0.38,Below Target,Low,Open,Retail,NaN,40,False
24,25,Yara Hall,North,SMB,Qualified,Monitor,Electronics,17000.0,10000,0.41,Target,Medium,Closed Won,Online,15-03-2026,40,True
25,26,Zach Allen,South,Consumer,Proposal,Dining Table,Furniture,38000.0,25000,0.34,Target,Medium,Open,Retail,NaN,40,True
26,27,alice johnson,north,Consumer,Prospecting,Laptop,Electronics,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,40,True
27,28,Ben Young,East,Corporate,Negotiation,Projector,electronics,27000.0,16000,0.41,Below Target,Low,Closed Lost,Online,22-03-2026,40,True
28,29,Chloe King,West,SMB,Qualified,Keyboard,Electronics,5000.0,2800,0.44,Target,Low,Open,Online,NaN,40,False
29,30,Daniel Wright,North,Corporate,Proposal,sofa,Furniture,48000.0,32000,0.33,Target,High,Closed Won,Retail,28-03-2026,40,True
30,31,Eva Lopez,South,Consumer,Negotiation,Tablet,Electronics,30000.0,20500,0.32,Target,Medium,Closed Won,Online,30-03-2026,40,True
31,32,Finn Hill,East,SMB,Prospecting,Mouse,Electronics,2800.0,1300,0.54,Below Target,Low,Open,Online,NaN,40,False
32,33,Gina Scott,West,Corporate,Qualified,Cabinet,Furniture,32000.0,22000,0.31,Target,Medium,Closed Won,Retail,05-04-2026,40,True
33,34,Harry Green,North,Consumer,Proposal,Camera,ELECTRONICS,42000.0,29000,0.31,Target,High,Open,Online,NaN,40,True
34,35,Isla Adams,South,Corporate,Negotiation,Conference Table,Furniture,68000.0,46000,0.32,Target,High,Closed Won,Retail,10-04-2026,40,True
35,36,Jon Baker,East,SMB,Qualified,Headphones,Electronics,9000.0,5200,0.42,Below Target,Low,Closed Lost,Online,12-04-2026,40,False
36,37,Kara Nelson,West,Consumer,Prospecting,Desk,Furniture,24000.0,16000,0.33,Target,Medium,Open,Retail,NaN,40,True
37,38,Leo Carter,North,Corporate,Qualified,Smart Watch,Electronics,13500.0,7600,0.44,Target,Medium,Closed Won,Online,18-04-2026,40,False
38,39,Maya Mitchell,South,SMB,Proposal,Bookshelf,Furniture,15500.0,9800,0.37,Target,Medium,Open,Retail,NaN,40,True
39,40,Nate Perez,East,Consumer,Negotiation,Webcam,Electronics,7500.0,4500,0.40,Below Target,Low,Closed Lost,Online,22-04-2026,40,False
40,41,Owen Roberts,West,Corporate,Qualified,Laptop,Electronics,60000.0,45500,0.24,Target,High,Closed Won,Online,26-04-2026,40,True
41,42,Paula Turner,north,SMB,Prospecting,Office Chair,Furniture,19000.0,12500,0.34,Target,Medium,Open,Retail,NaN,40,True
42,43,Reed Phillips,South,Consumer,Proposal,Mobile Phone,Electronics,33000.0,23000,0.30,Target,High,Closed Won,Online,30-04-2026,40,True
43,44,Sara Campbell,East,Corporate,Negotiation,Printer,Electronics,14000.0,8500,0.39,Below Target,Low,Closed Lost,Retail,02-05-2026,40,False
44,45,Tom Parker,West,SMB,Qualified,Monitor,Electronics,16000.0,9500,0.41,Target,Medium,Closed Won,Online,05-05-2026,40,True
45,46,Usha Evans,North,Consumer,Prospecting,Dining Table,Furniture,40000.0,27000,0.33,Target,Medium,Open,Retail,NaN,40,True
46,47,Vikram Edwards,South,Corporate,Qualified,Projector,Electronics,29000.0,17000,0.41,Target,High,Closed Won,online,10-05-2026,40,True
47,48,Willa Collins,East,SMB,Proposal,Keyboard,Electronics,5200.0,3000,NaN,Below Target,Low,Open,Online,NaN,40,False
48,49,Yusuf Stewart,West,Consumer,Negotiation,Sofa,Furniture,50000.0,34000,0.32,Target,High,Closed Won,Retail,15-05-2026,40,True
49,50,Zoe Sanchez,North,Corporate,Qualified,Cabinet,Furniture,34000.0,23000,0.32,Target,Medium,Closed Won,Retail,18-05-2026,40,True

In [19]:
#delete rows

data.drop(2)

,Customer ID,Customer Name,Region,Customer Segment,Sales Stage,Sales Date,Product,Category,Country,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date,Age,difference
0,1,alice johnson,NORTH,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,50,True
1,2,BOB SMITH,South,Corporate,Qualified,08-01-2026,Office Chair,Furniture,India,18000.0,12000,0.33,Target,Medium,Closed Won,Retail,15-01-2026,40,True
3,4,david lee,West,Corporate,Proposal,12-01-2026,Desk,Furniture,India,22000.0,15000,0.32,Target,Medium,Open,Retail,20-01-2026,40,True
4,5,EMILY BROWN,North,SMB,Prospecting,15-01-2026,Monitor,Electronics,India,15000.0,9000,0.40,Target,High,Open,Online,NaN,40,False
5,6,Frank Wilson,south,Consumer,Qualified,18-01-2026,Printer,electronics,India,12500.0,8000,0.36,Target,Medium,Closed Won,Retail,25-01-2026,40,False
6,7,grace miller,EAST,corporate,Negotiation,20-01-2026,Laptop,Electronics,India,58000.0,47000,0.19,Target,High,Closed Won,Online,28-01-2026,40,True
7,8,Henry Moore,west,SMB,Proposal,22-01-2026,Table,Furniture,India,26000.0,18000,0.31,Target,Medium,Open,Retail,NaN,40,True
8,9,Irene Taylor,NaN,consumer,Qualified,25-01-2026,Headphones,Electronics,India,8000.0,5000,0.38,Below Target,Low,Closed Lost,Online,02-02-2026,40,False
9,10,jack anderson,South,Corporate,Negotiation,28-01-2026,Sofa,Furniture,India,45000.0,30000,0.33,Target,High,Closed Won,Retail,05-02-2026,40,True
10,11,Karen Thomas,east,smb,Prospecting,01-02-2026,Keyboard,electronics,India,4500.0,2500,0.44,Target,Medium,Open,Online,NaN,40,False
11,12,Liam Jackson,West,Consumer,Qualified,03-02-2026,Tablet,Electronics,India,28000.0,19000,0.32,Target,High,Closed Won,Retail,10-02-2026,40,True
12,13,Mia White,North,Corporate,Proposal,05-02-2026,Cabinet,Furniture,India,30000.0,21000,0.30,Target,Medium,Open,Retail,NaN,40,True
13,14,NOAH HARRIS,South,consumer,Negotiation,08-02-2026,Smart Watch,Electronics,India,12000.0,7000,0.42,Below Target,Low,Closed Lost,Online,15-02-2026,40,False
14,15,Olivia Martin,East,SMB,Prospecting,10-02-2026,Mouse,Electronics,India,2500.0,1200,0.52,Target,Low,Open,Online,NaN,40,False
15,16,Peter Thompson,West,Corporate,Qualified,12-02-2026,Conference Table,Furniture,India,65000.0,45000,0.31,Target,High,Closed Won,Retail,20-02-2026,40,True
16,17,Quinn Garcia,North,Consumer,Proposal,15-02-2026,Camera,Electronics,India,40000.0,28000,0.30,Target,Medium,Open,Online,NaN,40,True
17,18,Rachel Martinez,South,Corporate,Negotiation,18-02-2026,Bookshelf,Furniture,India,14000.0,9000,0.36,Target,Medium,Closed Won,Retail,25-02-2026,40,False
18,19,Sam Robinson,East,SMB,Qualified,20-02-2026,Webcam,Electronics,India,NaN,4200,0.40,Below Target,Low,Closed Lost,Online,27-02-2026,40,False
19,20,Tina Clark,West,consumer,Prospecting,22-02-2026,Desk Lamp,Furniture,India,5500.0,3000,0.45,Target,Low,Open,Retail,NaN,40,False
20,21,Uma Rodriguez,North,Corporate,Qualified,25-02-2026,Laptop,Electronics,India,62000.0,48000,0.23,Target,High,Closed Won,Online,03-03-2026,40,True
21,22,Victor Lewis,South,SMB,Proposal,28-02-2026,Office Chair,Furniture,India,20000.0,13500,0.33,Target,Medium,Open,Retail,NaN,40,True
22,23,Wendy Lee,East,Consumer,Negotiation,02-03-2026,Mobile Phone,Electronics,India,35000.0,24000,0.31,Target,High,Closed Won,Online,09-03-2026,40,True
23,24,xavier walker,West,Corporate,prospecting,05-03-2026,Printer,Electronics,India,13000.0,8000,0.38,Below Target,Low,Open,Retail,NaN,40,False
24,25,Yara Hall,North,SMB,Qualified,08-03-2026,Monitor,Electronics,India,17000.0,10000,0.41,Target,Medium,Closed Won,Online,15-03-2026,40,True
25,26,Zach Allen,South,Consumer,Proposal,10-03-2026,Dining Table,Furniture,India,38000.0,25000,0.34,Target,Medium,Open,Retail,NaN,40,True
26,27,alice johnson,north,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,40,True
27,28,Ben Young,East,Corporate,Negotiation,15-03-2026,Projector,electronics,India,27000.0,16000,0.41,Below Target,Low,Closed Lost,Online,22-03-2026,40,True
28,29,Chloe King,West,SMB,Qualified,18-03-2026,Keyboard,Electronics,India,5000.0,2800,0.44,Target,Low,Open,Online,NaN,40,False
29,30,Daniel Wright,North,Corporate,Proposal,20-03-2026,sofa,Furniture,India,48000.0,32000,0.33,Target,High,Closed Won,Retail,28-03-2026,40,True
30,31,Eva Lopez,South,Consumer,Negotiation,22-03-2026,Tablet,Electronics,India,30000.0,20500,0.32,Target,Medium,Closed Won,Online,30-03-2026,40,True
31,32,Finn Hill,East,SMB,Prospecting,25-03-2026,Mouse,Electronics,India,2800.0,1300,0.54,Below Target,Low,Open,Online,NaN,40,False
32,33,Gina Scott,West,Corporate,Qualified,28-03-2026,Cabinet,Furniture,India,32000.0,22000,0.31,Target,Medium,Closed Won,Retail,05-04-2026,40,True
33,34,Harry Green,North,Consumer,Proposal,30-03-2026,Camera,ELECTRONICS,India,42000.0,29000,0.31,Target,High,Open,Online,NaN,40,True
34,35,Isla Adams,South,Corporate,Negotiation,02-04-2026,Conference Table,Furniture,India,68000.0,46000,0.32,Target,High,Closed Won,Retail,10-04-2026,40,True
35,36,Jon Baker,East,SMB,Qualified,05-04-2026,Headphones,Electronics,India,9000.0,5200,0.42,Below Target,Low,Closed Lost,Online,12-04-2026,40,False
36,37,Kara Nelson,West,Consumer,Prospecting,08-04-2026,Desk,Furniture,India,24000.0,16000,0.33,Target,Medium,Open,Retail,NaN,40,True
37,38,Leo Carter,North,Corporate,Qualified,10-04-2026,Smart Watch,Electronics,India,13500.0,7600,0.44,Target,Medium,Closed Won,Online,18-04-2026,40,False
38,39,Maya Mitchell,South,SMB,Proposal,12-04-2026,Bookshelf,Furniture,India,15500.0,9800,0.37,Target,Medium,Open,Retail,NaN,40,True
39,40,Nate Perez,East,Consumer,Negotiation,15-04-2026,Webcam,Electronics,India,7500.0,4500,0.40,Below Target,Low,Closed Lost,Online,22-04-2026,40,False
40,41,Owen Roberts,West,Corporate,Qualified,18-04-2026,Laptop,Electronics,India,60000.0,45500,0.24,Target,High,Closed Won,Online,26-04-2026,40,True
41,42,Paula Turner,north,SMB,Prospecting,20-04-2026,Office Chair,Furniture,India,19000.0,12500,0.34,Target,Medium,Open,Retail,NaN,40,True
42,43,Reed Phillips,South,Consumer,Proposal,22-04-2026,Mobile Phone,Electronics,India,33000.0,23000,0.30,Target,High,Closed Won,Online,30-04-2026,40,True
43,44,Sara Campbell,East,Corporate,Negotiation,not available,Printer,Electronics,India,14000.0,8500,0.39,Below Target,Low,Closed Lost,Retail,02-05-2026,40,False
44,45,Tom Parker,West,SMB,Qualified,28-04-2026,Monitor,Electronics,India,16000.0,9500,0.41,Target,Medium,Closed Won,Online,05-05-2026,40,True
45,46,Usha Evans,North,Consumer,Prospecting,01-05-2026,Dining Table,Furniture,India,40000.0,27000,0.33,Target,Medium,Open,Retail,NaN,40,True
46,47,Vikram Edwards,South,Corporate,Qualified,03-05-2026,Projector,Electronics,India,29000.0,17000,0.41,Target,High,Closed Won,online,10-05-2026,40,True
47,48,Willa Collins,East,SMB,Proposal,05-05-2026,Keyboard,Electronics,India,5200.0,3000,NaN,Below Target,Low,Open,Online,NaN,40,False
48,49,Yusuf Stewart,West,Consumer,Negotiation,08-05-2026,Sofa,Furniture,India,50000.0,34000,0.32,Target,High,Closed Won,Retail,15-05-2026,40,True
49,50,Zoe Sanchez,North,Corporate,Qualified,10-05-2026,Cabinet,Furniture,India,34000.0,23000,0.32,Target,Medium,Closed Won,Retail,18-05-2026,40,True

In [20]:
#isnull

data.isnull()

,Customer ID,Customer Name,Region,Customer Segment,Sales Stage,Sales Date,Product,Category,Country,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date,Age,difference
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
8,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
32,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
34,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
37,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
39,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
42,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
46,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False
48,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [21]:
data.isnull() .sum()

Customer ID          0
Customer Name        0
Region               1
Customer Segment     0
Sales Stage          0
Sales Date           0
Product              0
Category             0
Country              0
Sales                1
Cost                 0
Profit Margin        1
Target Status        0
Priority             0
Deal Status          0
Sales Channel        0
Close Date          19
Age                  0
difference           0
dtype: int64

In [24]:
data.notnull()

,Customer ID,Customer Name,Region,Customer Segment,Sales Stage,Sales Date,Product,Category,Country,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date,Age,difference
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
5,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
8,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
11,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
12,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
13,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
15,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
17,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
18,True,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
20,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
21,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
22,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
23,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
24,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
25,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
26,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
27,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
28,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
29,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
30,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
31,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
32,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
33,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
34,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
35,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
36,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
37,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
38,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
39,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
40,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
41,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
42,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
43,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
44,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
45,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True
46,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
47,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,True,False,True,True
48,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
49,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [25]:
data.dropna()

,Customer ID,Customer Name,Region,Customer Segment,Sales Stage,Sales Date,Product,Category,Country,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date,Age,difference
0,1,alice johnson,NORTH,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,50,True
1,2,BOB SMITH,South,Corporate,Qualified,08-01-2026,Office Chair,Furniture,India,18000.0,12000,0.33,Target,Medium,Closed Won,Retail,15-01-2026,40,True
3,4,david lee,West,Corporate,Proposal,12-01-2026,Desk,Furniture,India,22000.0,15000,0.32,Target,Medium,Open,Retail,20-01-2026,40,True
5,6,Frank Wilson,south,Consumer,Qualified,18-01-2026,Printer,electronics,India,12500.0,8000,0.36,Target,Medium,Closed Won,Retail,25-01-2026,40,False
6,7,grace miller,EAST,corporate,Negotiation,20-01-2026,Laptop,Electronics,India,58000.0,47000,0.19,Target,High,Closed Won,Online,28-01-2026,40,True
9,10,jack anderson,South,Corporate,Negotiation,28-01-2026,Sofa,Furniture,India,45000.0,30000,0.33,Target,High,Closed Won,Retail,05-02-2026,40,True
11,12,Liam Jackson,West,Consumer,Qualified,03-02-2026,Tablet,Electronics,India,28000.0,19000,0.32,Target,High,Closed Won,Retail,10-02-2026,40,True
13,14,NOAH HARRIS,South,consumer,Negotiation,08-02-2026,Smart Watch,Electronics,India,12000.0,7000,0.42,Below Target,Low,Closed Lost,Online,15-02-2026,40,False
15,16,Peter Thompson,West,Corporate,Qualified,12-02-2026,Conference Table,Furniture,India,65000.0,45000,0.31,Target,High,Closed Won,Retail,20-02-2026,40,True
17,18,Rachel Martinez,South,Corporate,Negotiation,18-02-2026,Bookshelf,Furniture,India,14000.0,9000,0.36,Target,Medium,Closed Won,Retail,25-02-2026,40,False
20,21,Uma Rodriguez,North,Corporate,Qualified,25-02-2026,Laptop,Electronics,India,62000.0,48000,0.23,Target,High,Closed Won,Online,03-03-2026,40,True
22,23,Wendy Lee,East,Consumer,Negotiation,02-03-2026,Mobile Phone,Electronics,India,35000.0,24000,0.31,Target,High,Closed Won,Online,09-03-2026,40,True
24,25,Yara Hall,North,SMB,Qualified,08-03-2026,Monitor,Electronics,India,17000.0,10000,0.41,Target,Medium,Closed Won,Online,15-03-2026,40,True
26,27,alice johnson,north,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,40,True
27,28,Ben Young,East,Corporate,Negotiation,15-03-2026,Projector,electronics,India,27000.0,16000,0.41,Below Target,Low,Closed Lost,Online,22-03-2026,40,True
29,30,Daniel Wright,North,Corporate,Proposal,20-03-2026,sofa,Furniture,India,48000.0,32000,0.33,Target,High,Closed Won,Retail,28-03-2026,40,True
30,31,Eva Lopez,South,Consumer,Negotiation,22-03-2026,Tablet,Electronics,India,30000.0,20500,0.32,Target,Medium,Closed Won,Online,30-03-2026,40,True
32,33,Gina Scott,West,Corporate,Qualified,28-03-2026,Cabinet,Furniture,India,32000.0,22000,0.31,Target,Medium,Closed Won,Retail,05-04-2026,40,True
34,35,Isla Adams,South,Corporate,Negotiation,02-04-2026,Conference Table,Furniture,India,68000.0,46000,0.32,Target,High,Closed Won,Retail,10-04-2026,40,True
35,36,Jon Baker,East,SMB,Qualified,05-04-2026,Headphones,Electronics,India,9000.0,5200,0.42,Below Target,Low,Closed Lost,Online,12-04-2026,40,False
37,38,Leo Carter,North,Corporate,Qualified,10-04-2026,Smart Watch,Electronics,India,13500.0,7600,0.44,Target,Medium,Closed Won,Online,18-04-2026,40,False
39,40,Nate Perez,East,Consumer,Negotiation,15-04-2026,Webcam,Electronics,India,7500.0,4500,0.40,Below Target,Low,Closed Lost,Online,22-04-2026,40,False
40,41,Owen Roberts,West,Corporate,Qualified,18-04-2026,Laptop,Electronics,India,60000.0,45500,0.24,Target,High,Closed Won,Online,26-04-2026,40,True
42,43,Reed Phillips,South,Consumer,Proposal,22-04-2026,Mobile Phone,Electronics,India,33000.0,23000,0.30,Target,High,Closed Won,Online,30-04-2026,40,True
43,44,Sara Campbell,East,Corporate,Negotiation,not available,Printer,Electronics,India,14000.0,8500,0.39,Below Target,Low,Closed Lost,Retail,02-05-2026,40,False
44,45,Tom Parker,West,SMB,Qualified,28-04-2026,Monitor,Electronics,India,16000.0,9500,0.41,Target,Medium,Closed Won,Online,05-05-2026,40,True
46,47,Vikram Edwards,South,Corporate,Qualified,03-05-2026,Projector,Electronics,India,29000.0,17000,0.41,Target,High,Closed Won,online,10-05-2026,40,True
48,49,Yusuf Stewart,West,Consumer,Negotiation,08-05-2026,Sofa,Furniture,India,50000.0,34000,0.32,Target,High,Closed Won,Retail,15-05-2026,40,True
49,50,Zoe Sanchez,North,Corporate,Qualified,10-05-2026,Cabinet,Furniture,India,34000.0,23000,0.32,Target,Medium,Closed Won,Retail,18-05-2026,40,True

In [26]:
data.fillna(0)

,Customer ID,Customer Name,Region,Customer Segment,Sales Stage,Sales Date,Product,Category,Country,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date,Age,difference
0,1,alice johnson,NORTH,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,50,True
1,2,BOB SMITH,South,Corporate,Qualified,08-01-2026,Office Chair,Furniture,India,18000.0,12000,0.33,Target,Medium,Closed Won,Retail,15-01-2026,40,True
2,3,Carol Davis,east,consumer,Negotiation,10-01-2026,Mobile Phone,electronics,India,32000.0,35000,-0.09,Below Target,Low,Closed Lost,Online,0,40,True
3,4,david lee,West,Corporate,Proposal,12-01-2026,Desk,Furniture,India,22000.0,15000,0.32,Target,Medium,Open,Retail,20-01-2026,40,True
4,5,EMILY BROWN,North,SMB,Prospecting,15-01-2026,Monitor,Electronics,India,15000.0,9000,0.40,Target,High,Open,Online,0,40,False
5,6,Frank Wilson,south,Consumer,Qualified,18-01-2026,Printer,electronics,India,12500.0,8000,0.36,Target,Medium,Closed Won,Retail,25-01-2026,40,False
6,7,grace miller,EAST,corporate,Negotiation,20-01-2026,Laptop,Electronics,India,58000.0,47000,0.19,Target,High,Closed Won,Online,28-01-2026,40,True
7,8,Henry Moore,west,SMB,Proposal,22-01-2026,Table,Furniture,India,26000.0,18000,0.31,Target,Medium,Open,Retail,0,40,True
8,9,Irene Taylor,0,consumer,Qualified,25-01-2026,Headphones,Electronics,India,8000.0,5000,0.38,Below Target,Low,Closed Lost,Online,02-02-2026,40,False
9,10,jack anderson,South,Corporate,Negotiation,28-01-2026,Sofa,Furniture,India,45000.0,30000,0.33,Target,High,Closed Won,Retail,05-02-2026,40,True
10,11,Karen Thomas,east,smb,Prospecting,01-02-2026,Keyboard,electronics,India,4500.0,2500,0.44,Target,Medium,Open,Online,0,40,False
11,12,Liam Jackson,West,Consumer,Qualified,03-02-2026,Tablet,Electronics,India,28000.0,19000,0.32,Target,High,Closed Won,Retail,10-02-2026,40,True
12,13,Mia White,North,Corporate,Proposal,05-02-2026,Cabinet,Furniture,India,30000.0,21000,0.30,Target,Medium,Open,Retail,0,40,True
13,14,NOAH HARRIS,South,consumer,Negotiation,08-02-2026,Smart Watch,Electronics,India,12000.0,7000,0.42,Below Target,Low,Closed Lost,Online,15-02-2026,40,False
14,15,Olivia Martin,East,SMB,Prospecting,10-02-2026,Mouse,Electronics,India,2500.0,1200,0.52,Target,Low,Open,Online,0,40,False
15,16,Peter Thompson,West,Corporate,Qualified,12-02-2026,Conference Table,Furniture,India,65000.0,45000,0.31,Target,High,Closed Won,Retail,20-02-2026,40,True
16,17,Quinn Garcia,North,Consumer,Proposal,15-02-2026,Camera,Electronics,India,40000.0,28000,0.30,Target,Medium,Open,Online,0,40,True
17,18,Rachel Martinez,South,Corporate,Negotiation,18-02-2026,Bookshelf,Furniture,India,14000.0,9000,0.36,Target,Medium,Closed Won,Retail,25-02-2026,40,False
18,19,Sam Robinson,East,SMB,Qualified,20-02-2026,Webcam,Electronics,India,0.0,4200,0.40,Below Target,Low,Closed Lost,Online,27-02-2026,40,False
19,20,Tina Clark,West,consumer,Prospecting,22-02-2026,Desk Lamp,Furniture,India,5500.0,3000,0.45,Target,Low,Open,Retail,0,40,False
20,21,Uma Rodriguez,North,Corporate,Qualified,25-02-2026,Laptop,Electronics,India,62000.0,48000,0.23,Target,High,Closed Won,Online,03-03-2026,40,True
21,22,Victor Lewis,South,SMB,Proposal,28-02-2026,Office Chair,Furniture,India,20000.0,13500,0.33,Target,Medium,Open,Retail,0,40,True
22,23,Wendy Lee,East,Consumer,Negotiation,02-03-2026,Mobile Phone,Electronics,India,35000.0,24000,0.31,Target,High,Closed Won,Online,09-03-2026,40,True
23,24,xavier walker,West,Corporate,prospecting,05-03-2026,Printer,Electronics,India,13000.0,8000,0.38,Below Target,Low,Open,Retail,0,40,False
24,25,Yara Hall,North,SMB,Qualified,08-03-2026,Monitor,Electronics,India,17000.0,10000,0.41,Target,Medium,Closed Won,Online,15-03-2026,40,True
25,26,Zach Allen,South,Consumer,Proposal,10-03-2026,Dining Table,Furniture,India,38000.0,25000,0.34,Target,Medium,Open,Retail,0,40,True
26,27,alice johnson,north,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,40,True
27,28,Ben Young,East,Corporate,Negotiation,15-03-2026,Projector,electronics,India,27000.0,16000,0.41,Below Target,Low,Closed Lost,Online,22-03-2026,40,True
28,29,Chloe King,West,SMB,Qualified,18-03-2026,Keyboard,Electronics,India,5000.0,2800,0.44,Target,Low,Open,Online,0,40,False
29,30,Daniel Wright,North,Corporate,Proposal,20-03-2026,sofa,Furniture,India,48000.0,32000,0.33,Target,High,Closed Won,Retail,28-03-2026,40,True
30,31,Eva Lopez,South,Consumer,Negotiation,22-03-2026,Tablet,Electronics,India,30000.0,20500,0.32,Target,Medium,Closed Won,Online,30-03-2026,40,True
31,32,Finn Hill,East,SMB,Prospecting,25-03-2026,Mouse,Electronics,India,2800.0,1300,0.54,Below Target,Low,Open,Online,0,40,False
32,33,Gina Scott,West,Corporate,Qualified,28-03-2026,Cabinet,Furniture,India,32000.0,22000,0.31,Target,Medium,Closed Won,Retail,05-04-2026,40,True
33,34,Harry Green,North,Consumer,Proposal,30-03-2026,Camera,ELECTRONICS,India,42000.0,29000,0.31,Target,High,Open,Online,0,40,True
34,35,Isla Adams,South,Corporate,Negotiation,02-04-2026,Conference Table,Furniture,India,68000.0,46000,0.32,Target,High,Closed Won,Retail,10-04-2026,40,True
35,36,Jon Baker,East,SMB,Qualified,05-04-2026,Headphones,Electronics,India,9000.0,5200,0.42,Below Target,Low,Closed Lost,Online,12-04-2026,40,False
36,37,Kara Nelson,West,Consumer,Prospecting,08-04-2026,Desk,Furniture,India,24000.0,16000,0.33,Target,Medium,Open,Retail,0,40,True
37,38,Leo Carter,North,Corporate,Qualified,10-04-2026,Smart Watch,Electronics,India,13500.0,7600,0.44,Target,Medium,Closed Won,Online,18-04-2026,40,False
38,39,Maya Mitchell,South,SMB,Proposal,12-04-2026,Bookshelf,Furniture,India,15500.0,9800,0.37,Target,Medium,Open,Retail,0,40,True
39,40,Nate Perez,East,Consumer,Negotiation,15-04-2026,Webcam,Electronics,India,7500.0,4500,0.40,Below Target,Low,Closed Lost,Online,22-04-2026,40,False
40,41,Owen Roberts,West,Corporate,Qualified,18-04-2026,Laptop,Electronics,India,60000.0,45500,0.24,Target,High,Closed Won,Online,26-04-2026,40,True
41,42,Paula Turner,north,SMB,Prospecting,20-04-2026,Office Chair,Furniture,India,19000.0,12500,0.34,Target,Medium,Open,Retail,0,40,True
42,43,Reed Phillips,South,Consumer,Proposal,22-04-2026,Mobile Phone,Electronics,India,33000.0,23000,0.30,Target,High,Closed Won,Online,30-04-2026,40,True
43,44,Sara Campbell,East,Corporate,Negotiation,not available,Printer,Electronics,India,14000.0,8500,0.39,Below Target,Low,Closed Lost,Retail,02-05-2026,40,False
44,45,Tom Parker,West,SMB,Qualified,28-04-2026,Monitor,Electronics,India,16000.0,9500,0.41,Target,Medium,Closed Won,Online,05-05-2026,40,True
45,46,Usha Evans,North,Consumer,Prospecting,01-05-2026,Dining Table,Furniture,India,40000.0,27000,0.33,Target,Medium,Open,Retail,0,40,True
46,47,Vikram Edwards,South,Corporate,Qualified,03-05-2026,Projector,Electronics,India,29000.0,17000,0.41,Target,High,Closed Won,online,10-05-2026,40,True
47,48,Willa Collins,East,SMB,Proposal,05-05-2026,Keyboard,Electronics,India,5200.0,3000,0.00,Below Target,Low,Open,Online,0,40,False
48,49,Yusuf Stewart,West,Consumer,Negotiation,08-05-2026,Sofa,Furniture,India,50000.0,34000,0.32,Target,High,Closed Won,Retail,15-05-2026,40,True
49,50,Zoe Sanchez,North,Corporate,Qualified,10-05-2026,Cabinet,Furniture,India,34000.0,23000,0.32,Target,Medium,Closed Won,Retail,18-05-2026,40,True

In [27]:
data.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [28]:
data.drop_duplicates()

,Customer ID,Customer Name,Region,Customer Segment,Sales Stage,Sales Date,Product,Category,Country,Sales,Cost,Profit Margin,Target Status,Priority,Deal Status,Sales Channel,Close Date,Age,difference
0,1,alice johnson,NORTH,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,50,True
1,2,BOB SMITH,South,Corporate,Qualified,08-01-2026,Office Chair,Furniture,India,18000.0,12000,0.33,Target,Medium,Closed Won,Retail,15-01-2026,40,True
2,3,Carol Davis,east,consumer,Negotiation,10-01-2026,Mobile Phone,electronics,India,32000.0,35000,-0.09,Below Target,Low,Closed Lost,Online,NaN,40,True
3,4,david lee,West,Corporate,Proposal,12-01-2026,Desk,Furniture,India,22000.0,15000,0.32,Target,Medium,Open,Retail,20-01-2026,40,True
4,5,EMILY BROWN,North,SMB,Prospecting,15-01-2026,Monitor,Electronics,India,15000.0,9000,0.40,Target,High,Open,Online,NaN,40,False
5,6,Frank Wilson,south,Consumer,Qualified,18-01-2026,Printer,electronics,India,12500.0,8000,0.36,Target,Medium,Closed Won,Retail,25-01-2026,40,False
6,7,grace miller,EAST,corporate,Negotiation,20-01-2026,Laptop,Electronics,India,58000.0,47000,0.19,Target,High,Closed Won,Online,28-01-2026,40,True
7,8,Henry Moore,west,SMB,Proposal,22-01-2026,Table,Furniture,India,26000.0,18000,0.31,Target,Medium,Open,Retail,NaN,40,True
8,9,Irene Taylor,NaN,consumer,Qualified,25-01-2026,Headphones,Electronics,India,8000.0,5000,0.38,Below Target,Low,Closed Lost,Online,02-02-2026,40,False
9,10,jack anderson,South,Corporate,Negotiation,28-01-2026,Sofa,Furniture,India,45000.0,30000,0.33,Target,High,Closed Won,Retail,05-02-2026,40,True
10,11,Karen Thomas,east,smb,Prospecting,01-02-2026,Keyboard,electronics,India,4500.0,2500,0.44,Target,Medium,Open,Online,NaN,40,False
11,12,Liam Jackson,West,Consumer,Qualified,03-02-2026,Tablet,Electronics,India,28000.0,19000,0.32,Target,High,Closed Won,Retail,10-02-2026,40,True
12,13,Mia White,North,Corporate,Proposal,05-02-2026,Cabinet,Furniture,India,30000.0,21000,0.30,Target,Medium,Open,Retail,NaN,40,True
13,14,NOAH HARRIS,South,consumer,Negotiation,08-02-2026,Smart Watch,Electronics,India,12000.0,7000,0.42,Below Target,Low,Closed Lost,Online,15-02-2026,40,False
14,15,Olivia Martin,East,SMB,Prospecting,10-02-2026,Mouse,Electronics,India,2500.0,1200,0.52,Target,Low,Open,Online,NaN,40,False
15,16,Peter Thompson,West,Corporate,Qualified,12-02-2026,Conference Table,Furniture,India,65000.0,45000,0.31,Target,High,Closed Won,Retail,20-02-2026,40,True
16,17,Quinn Garcia,North,Consumer,Proposal,15-02-2026,Camera,Electronics,India,40000.0,28000,0.30,Target,Medium,Open,Online,NaN,40,True
17,18,Rachel Martinez,South,Corporate,Negotiation,18-02-2026,Bookshelf,Furniture,India,14000.0,9000,0.36,Target,Medium,Closed Won,Retail,25-02-2026,40,False
18,19,Sam Robinson,East,SMB,Qualified,20-02-2026,Webcam,Electronics,India,NaN,4200,0.40,Below Target,Low,Closed Lost,Online,27-02-2026,40,False
19,20,Tina Clark,West,consumer,Prospecting,22-02-2026,Desk Lamp,Furniture,India,5500.0,3000,0.45,Target,Low,Open,Retail,NaN,40,False
20,21,Uma Rodriguez,North,Corporate,Qualified,25-02-2026,Laptop,Electronics,India,62000.0,48000,0.23,Target,High,Closed Won,Online,03-03-2026,40,True
21,22,Victor Lewis,South,SMB,Proposal,28-02-2026,Office Chair,Furniture,India,20000.0,13500,0.33,Target,Medium,Open,Retail,NaN,40,True
22,23,Wendy Lee,East,Consumer,Negotiation,02-03-2026,Mobile Phone,Electronics,India,35000.0,24000,0.31,Target,High,Closed Won,Online,09-03-2026,40,True
23,24,xavier walker,West,Corporate,prospecting,05-03-2026,Printer,Electronics,India,13000.0,8000,0.38,Below Target,Low,Open,Retail,NaN,40,False
24,25,Yara Hall,North,SMB,Qualified,08-03-2026,Monitor,Electronics,India,17000.0,10000,0.41,Target,Medium,Closed Won,Online,15-03-2026,40,True
25,26,Zach Allen,South,Consumer,Proposal,10-03-2026,Dining Table,Furniture,India,38000.0,25000,0.34,Target,Medium,Open,Retail,NaN,40,True
26,27,alice johnson,north,Consumer,Prospecting,05-01-2026,Laptop,Electronics,India,50000.0,42000,0.16,Target,High,Closed Won,Online,12-01-2026,40,True
27,28,Ben Young,East,Corporate,Negotiation,15-03-2026,Projector,electronics,India,27000.0,16000,0.41,Below Target,Low,Closed Lost,Online,22-03-2026,40,True
28,29,Chloe King,West,SMB,Qualified,18-03-2026,Keyboard,Electronics,India,5000.0,2800,0.44,Target,Low,Open,Online,NaN,40,False
29,30,Daniel Wright,North,Corporate,Proposal,20-03-2026,sofa,Furniture,India,48000.0,32000,0.33,Target,High,Closed Won,Retail,28-03-2026,40,True
30,31,Eva Lopez,South,Consumer,Negotiation,22-03-2026,Tablet,Electronics,India,30000.0,20500,0.32,Target,Medium,Closed Won,Online,30-03-2026,40,True
31,32,Finn Hill,East,SMB,Prospecting,25-03-2026,Mouse,Electronics,India,2800.0,1300,0.54,Below Target,Low,Open,Online,NaN,40,False
32,33,Gina Scott,West,Corporate,Qualified,28-03-2026,Cabinet,Furniture,India,32000.0,22000,0.31,Target,Medium,Closed Won,Retail,05-04-2026,40,True
33,34,Harry Green,North,Consumer,Proposal,30-03-2026,Camera,ELECTRONICS,India,42000.0,29000,0.31,Target,High,Open,Online,NaN,40,True
34,35,Isla Adams,South,Corporate,Negotiation,02-04-2026,Conference Table,Furniture,India,68000.0,46000,0.32,Target,High,Closed Won,Retail,10-04-2026,40,True
35,36,Jon Baker,East,SMB,Qualified,05-04-2026,Headphones,Electronics,India,9000.0,5200,0.42,Below Target,Low,Closed Lost,Online,12-04-2026,40,False
36,37,Kara Nelson,West,Consumer,Prospecting,08-04-2026,Desk,Furniture,India,24000.0,16000,0.33,Target,Medium,Open,Retail,NaN,40,True
37,38,Leo Carter,North,Corporate,Qualified,10-04-2026,Smart Watch,Electronics,India,13500.0,7600,0.44,Target,Medium,Closed Won,Online,18-04-2026,40,False
38,39,Maya Mitchell,South,SMB,Proposal,12-04-2026,Bookshelf,Furniture,India,15500.0,9800,0.37,Target,Medium,Open,Retail,NaN,40,True
39,40,Nate Perez,East,Consumer,Negotiation,15-04-2026,Webcam,Electronics,India,7500.0,4500,0.40,Below Target,Low,Closed Lost,Online,22-04-2026,40,False
40,41,Owen Roberts,West,Corporate,Qualified,18-04-2026,Laptop,Electronics,India,60000.0,45500,0.24,Target,High,Closed Won,Online,26-04-2026,40,True
41,42,Paula Turner,north,SMB,Prospecting,20-04-2026,Office Chair,Furniture,India,19000.0,12500,0.34,Target,Medium,Open,Retail,NaN,40,True
42,43,Reed Phillips,South,Consumer,Proposal,22-04-2026,Mobile Phone,Electronics,India,33000.0,23000,0.30,Target,High,Closed Won,Online,30-04-2026,40,True
43,44,Sara Campbell,East,Corporate,Negotiation,not available,Printer,Electronics,India,14000.0,8500,0.39,Below Target,Low,Closed Lost,Retail,02-05-2026,40,False
44,45,Tom Parker,West,SMB,Qualified,28-04-2026,Monitor,Electronics,India,16000.0,9500,0.41,Target,Medium,Closed Won,Online,05-05-2026,40,True
45,46,Usha Evans,North,Consumer,Prospecting,01-05-2026,Dining Table,Furniture,India,40000.0,27000,0.33,Target,Medium,Open,Retail,NaN,40,True
46,47,Vikram Edwards,South,Corporate,Qualified,03-05-2026,Projector,Electronics,India,29000.0,17000,0.41,Target,High,Closed Won,online,10-05-2026,40,True
47,48,Willa Collins,East,SMB,Proposal,05-05-2026,Keyboard,Electronics,India,5200.0,3000,NaN,Below Target,Low,Open,Online,NaN,40,False
48,49,Yusuf Stewart,West,Consumer,Negotiation,08-05-2026,Sofa,Furniture,India,50000.0,34000,0.32,Target,High,Closed Won,Retail,15-05-2026,40,True
49,50,Zoe Sanchez,North,Corporate,Qualified,10-05-2026,Cabinet,Furniture,India,34000.0,23000,0.32,Target,Medium,Closed Won,Retail,18-05-2026,40,True

In [31]:
#value counts

data["Category"].value_counts()

Category
Electronics    26
Furniture      19
electronics     4
ELECTRONICS     1
Name: count, dtype: int64

In [32]:
#unique count

data["Category"].nunique()

4

In [34]:
#mathematical operations
data['Age'] .sum()

np.int64(2010)

In [38]:
#mean
print("mean:",data['Cost'] .mean())
#max
print("max:",data['Cost'].max())
#min
print("min:",data['Cost'].min())
#count
print("count:",data['Cost'].count())
#median
print("median:",data['Cost'].median())
#std
print("std:",data['Cost'].std())
#var
print("var:",data['Cost'].var())

mean: 18942.0
max: 48000
min: 1200
count: 50
median: 16000.0
std: 14033.110845425543
var: 196928200.0

In [42]:
#aggregate function

data.agg({'Cost':["sum","mean","max","min","count","median","std","var"]})

                Cost
sum     9.471000e+05
mean    1.894200e+04
max     4.800000e+04
min     1.200000e+03
count   5.000000e+01
median  1.600000e+04
std     1.403311e+04
var     1.969282e+08

In [43]:
data.groupby("Sales")["Age"].mean()

Sales
2500.0     40.000000
2800.0     40.000000
4500.0     40.000000
5000.0     40.000000
5200.0     40.000000
5500.0     40.000000
7500.0     40.000000
8000.0     40.000000
9000.0     40.000000
12000.0    40.000000
12500.0    40.000000
13000.0    40.000000
13500.0    40.000000
14000.0    40.000000
15000.0    40.000000
15500.0    40.000000
16000.0    40.000000
17000.0    40.000000
18000.0    40.000000
19000.0    40.000000
20000.0    40.000000
22000.0    40.000000
24000.0    40.000000
26000.0    40.000000
27000.0    40.000000
28000.0    40.000000
29000.0    40.000000
30000.0    40.000000
32000.0    40.000000
33000.0    40.000000
34000.0    40.000000
35000.0    40.000000
38000.0    40.000000
40000.0    40.000000
42000.0    40.000000
45000.0    40.000000
48000.0    40.000000
50000.0    43.333333
58000.0    40.000000
60000.0    40.000000
62000.0    40.000000
65000.0    40.000000
68000.0    40.000000
Name: Age, dtype: float64

In [47]:
data.groupby(["Cost","Sales"]) ["Age"].mean()

Cost   Sales
1200   2500.0     40.0
1300   2800.0     40.0
2500   4500.0     40.0
2800   5000.0     40.0
3000   5200.0     40.0
       5500.0     40.0
4500   7500.0     40.0
5000   8000.0     40.0
5200   9000.0     40.0
7000   12000.0    40.0
7600   13500.0    40.0
8000   12500.0    40.0
       13000.0    40.0
8500   14000.0    40.0
9000   14000.0    40.0
       15000.0    40.0
9500   16000.0    40.0
9800   15500.0    40.0
10000  17000.0    40.0
12000  18000.0    40.0
12500  19000.0    40.0
13500  20000.0    40.0
15000  22000.0    40.0
16000  24000.0    40.0
       27000.0    40.0
17000  29000.0    40.0
18000  26000.0    40.0
19000  28000.0    40.0
20500  30000.0    40.0
21000  30000.0    40.0
22000  32000.0    40.0
23000  33000.0    40.0
       34000.0    40.0
24000  35000.0    40.0
25000  38000.0    40.0
27000  40000.0    40.0
28000  40000.0    40.0
29000  42000.0    40.0
30000  45000.0    40.0
32000  48000.0    40.0
34000  50000.0    40.0
35000  32000.0    40.0
42000  50000.0    45.0
45000  65000.0    40.0
45500  60000.0    40.0
46000  68000.0    40.0
47000  58000.0    40.0
48000  62000.0    40.0
Name: Age, dtype: float64

In [48]:
#apply function

data["Age"].apply(lambda x:x+5)

0     55
1     45
2     45
3     45
4     45
5     45
6     45
7     45
8     45
9     45
10    45
11    45
12    45
13    45
14    45
15    45
16    45
17    45
18    45
19    45
20    45
21    45
22    45
23    45
24    45
25    45
26    45
27    45
28    45
29    45
30    45
31    45
32    45
33    45
34    45
35    45
36    45
37    45
38    45
39    45
40    45
41    45
42    45
43    45
44    45
45    45
46    45
47    45
48    45
49    45
Name: Age, dtype: int64