In [3]:
import pandas as pd
data = pd.read_csv("sampledata.csv")
data

,Excel Sample Data,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Inventory Records Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Product ID,Product Name,Opening \nStock,Purchase/\nStock in,Number of \nUnits Sold,Hand-In-\nStock,Cost Price \nPer Unit (USD),Cost Price\nTotal (USD)
4,P101,Laptop,50,20,10,60,1200,72000
5,P102,Monitor,40,15,5,50,500,25000
6,P103,Keyboard,60,25,15,70,50,3500
7,P104,Headphones,30,10,3,37,100,3700
8,P105,Smartphone,70,30,20,80,900,72000
9,P106,Tablet,45,18,8,55,700,38500
10,P107,Router,55,22,12,65,150,9750
11,P108,External Hard Drive,25,12,5,32,200,6400
12,P109,Wireless Earbuds,35,15,7,43,80,3440
13,P110,Webcam,40,20,10,50,60,3000
14,P111,Desk Chair,20,8,3,25,150,3750
15,P112,Desk Lamp,30,15,7,38,30,1140
16,P113,USB Flash Drive,50,25,12,63,20,1260
17,P114,Ethernet Cable,60,30,15,75,10,750
18,P115,Power Strip,40,20,8,52,25,1300
19,P116,Wireless Mouse,35,15,5,45,40,1800
20,P117,Gaming Keyboard,25,10,4,31,100,3100
21,P118,Gaming Mouse,30,12,6,36,80,2880
22,P119,Gaming Headset,20,8,3,25,120,3000
23,P120,Gaming Chair,15,6,2,19,200,3800
24,P121,Gaming Monitor,25,10,4,29,400,11600
25,P122,Graphics Card,40,18,9,49,600,29400
26,P123,CPU,30,15,7,38,350,13300
27,P124,Motherboard,25,12,5,32,200,6400
28,P125,RAM,50,22,11,61,80,4880
29,P126,SSD,45,20,8,57,120,6840
30,P127,HDD,60,25,12,73,60,4380
31,P128,Power Supply,35,15,6,44,100,4400
32,P129,PC Case,40,18,9,49,80,3920
33,P130,CPU Cooler,30,12,4,34,50,1700
34,P131,Monitor Stand,25,10,3,28,30,840
35,P132,Mouse Pad,50,20,8,58,10,580
36,P133,Thermal Paste,40,15,5,50,5,250
37,P134,Cable Management Kit,30,12,4,34,15,510
38,P135,WiFi Adapter,20,8,3,23,20,460
39,P136,External DVD Drive,15,6,2,17,50,850
40,P137,Printer Cable,25,10,4,29,5,145
41,P138,Keyboard Cleaner,40,18,9,49,8,392
42,P139,Laptop Cooling Pad,30,15,6,39,20,780
43,P140,USB Hub,35,12,4,31,15,465
44,P141,Anti-Glare Screen Protector,25,8,3,28,10,280
45,P142,USB-C Adapter,20,10,4,24,15,360
46,P143,Laptop Sleeve,30,12,5,37,20,740
47,P144,Wireless Charger,40,18,7,51,30,1530
48,P145,USB-C Cable,50,20,9,61,8,488
49,P146,Gaming Desk,25,10,3,28,150,4200

In [ ]:
#view data - head
data.head(15)

,Excel Sample Data,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Inventory Records Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Product ID,Product Name,Opening \nStock,Purchase/\nStock in,Number of \nUnits Sold,Hand-In-\nStock,Cost Price \nPer Unit (USD),Cost Price\nTotal (USD)
4,P101,Laptop,50,20,10,60,1200,72000
5,P102,Monitor,40,15,5,50,500,25000
6,P103,Keyboard,60,25,15,70,50,3500
7,P104,Headphones,30,10,3,37,100,3700
8,P105,Smartphone,70,30,20,80,900,72000
9,P106,Tablet,45,18,8,55,700,38500
10,P107,Router,55,22,12,65,150,9750
11,P108,External Hard Drive,25,12,5,32,200,6400
12,P109,Wireless Earbuds,35,15,7,43,80,3440
13,P110,Webcam,40,20,10,50,60,3000
14,P111,Desk Chair,20,8,3,25,150,3750

In [9]:
#tail - last five

data.tail(5)

,Excel Sample Data,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
45,P142,USB-C Adapter,20,10,4,24,15,360
46,P143,Laptop Sleeve,30,12,5,37,20,740
47,P144,Wireless Charger,40,18,7,51,30,1530
48,P145,USB-C Cable,50,20,9,61,8,488
49,P146,Gaming Desk,25,10,3,28,150,4200

In [ ]:
#random - sample means
data.sample(3)

,Excel Sample Data,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
34,P131,Monitor Stand,25,10,3,28,30,840
39,P136,External DVD Drive,15,6,2,17,50,850
13,P110,Webcam,40,20,10,50,60,3000

In [13]:
#data information
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Excel Sample Data  48 non-null     object
 1   Unnamed: 1         47 non-null     object
 2   Unnamed: 2         47 non-null     object
 3   Unnamed: 3         47 non-null     object
 4   Unnamed: 4         47 non-null     object
 5   Unnamed: 5         47 non-null     object
 6   Unnamed: 6         47 non-null     object
 7   Unnamed: 7         47 non-null     object
dtypes: object(8)
memory usage: 3.3+ KB

In [14]:
#describe

data.describe()

,Excel Sample Data,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
count,48,47,47,47,47,47,47,47
unique,48,47,12,11,14,33,23,44
top,Inventory Records Data,Product Name,40,15,3,50,80,72000
freq,1,1,8,8,7,3,4,2

In [21]:
#shape

i = data.shape
j = data.size
k = data.ndim
print("shape",i)
print("size",j)
print("dimension",k)

shape (50, 8)
size 400
dimension 2

In [20]:
#no of dimension - ndim

data.ndim

2

In [ ]:
#columns 
data.columns

Index(['Excel Sample Data', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7'],
      dtype='object')

In [ ]:
#index
data.index

RangeIndex(start=0, stop=50, step=1)

In [ ]:
#datatypes
data.dtypes

Excel Sample Data    object
Unnamed: 1           object
Unnamed: 2           object
Unnamed: 3           object
Unnamed: 4           object
Unnamed: 5           object
Unnamed: 6           object
Unnamed: 7           object
dtype: object

In [36]:
#selecting columns

data[["Unnamed: 2","Unnamed: 3"]]

         Unnamed: 2           Unnamed: 3
0               NaN                  NaN
1               NaN                  NaN
2               NaN                  NaN
3   Opening \nStock  Purchase/\nStock in
4                50                   20
5                40                   15
6                60                   25
7                30                   10
8                70                   30
9                45                   18
10               55                   22
11               25                   12
12               35                   15
13               40                   20
14               20                    8
15               30                   15
16               50                   25
17               60                   30
18               40                   20
19               35                   15
20               25                   10
21               30                   12
22               20                    8
23               15                    6
24               25                   10
25               40                   18
26               30                   15
27               25                   12
28               50                   22
29               45                   20
30               60                   25
31               35                   15
32               40                   18
33               30                   12
34               25                   10
35               50                   20
36               40                   15
37               30                   12
38               20                    8
39               15                    6
40               25                   10
41               40                   18
42               30                   15
43               35                   12
44               25                    8
45               20                   10
46               30                   12
47               40                   18
48               50                   20
49               25                   10

In [46]:
#selecting rows
data.loc[3]

Excel Sample Data                     Product ID
Unnamed: 1                          Product Name
Unnamed: 2                       Opening \nStock
Unnamed: 3                   Purchase/\nStock in
Unnamed: 4                Number of \nUnits Sold
Unnamed: 5                       Hand-In-\nStock
Unnamed: 6           Cost Price \nPer Unit (USD)
Unnamed: 7               Cost Price\nTotal (USD)
Name: 3, dtype: object

In [45]:
#loc - select rows and columns using index lables
#iloc - selecting rows and columns using interger positions
data.iloc[3]

#position 3 means the 4th row
#iloc[] always start counting from 0

Excel Sample Data                     Product ID
Unnamed: 1                          Product Name
Unnamed: 2                       Opening \nStock
Unnamed: 3                   Purchase/\nStock in
Unnamed: 4                Number of \nUnits Sold
Unnamed: 5                       Hand-In-\nStock
Unnamed: 6           Cost Price \nPer Unit (USD)
Unnamed: 7               Cost Price\nTotal (USD)
Name: 3, dtype: object

In [54]:
data.set_index("Unnamed: 2")

,Excel Sample Data,Unnamed: 1,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
Unnamed: 2,,,,,,,
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Inventory Records Data,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Opening \nStock,Product ID,Product Name,Purchase/\nStock in,Number of \nUnits Sold,Hand-In-\nStock,Cost Price \nPer Unit (USD),Cost Price\nTotal (USD)
50,P101,Laptop,20,10,60,1200,72000
40,P102,Monitor,15,5,50,500,25000
60,P103,Keyboard,25,15,70,50,3500
30,P104,Headphones,10,3,37,100,3700
70,P105,Smartphone,30,20,80,900,72000
45,P106,Tablet,18,8,55,700,38500
55,P107,Router,22,12,65,150,9750
25,P108,External Hard Drive,12,5,32,200,6400
35,P109,Wireless Earbuds,15,7,43,80,3440
40,P110,Webcam,20,10,50,60,3000
20,P111,Desk Chair,8,3,25,150,3750
30,P112,Desk Lamp,15,7,38,30,1140
50,P113,USB Flash Drive,25,12,63,20,1260
60,P114,Ethernet Cable,30,15,75,10,750
40,P115,Power Strip,20,8,52,25,1300
35,P116,Wireless Mouse,15,5,45,40,1800
25,P117,Gaming Keyboard,10,4,31,100,3100
30,P118,Gaming Mouse,12,6,36,80,2880
20,P119,Gaming Headset,8,3,25,120,3000
15,P120,Gaming Chair,6,2,19,200,3800
25,P121,Gaming Monitor,10,4,29,400,11600
40,P122,Graphics Card,18,9,49,600,29400
30,P123,CPU,15,7,38,350,13300
25,P124,Motherboard,12,5,32,200,6400
50,P125,RAM,22,11,61,80,4880
45,P126,SSD,20,8,57,120,6840
60,P127,HDD,25,12,73,60,4380
35,P128,Power Supply,15,6,44,100,4400
40,P129,PC Case,18,9,49,80,3920
30,P130,CPU Cooler,12,4,34,50,1700
25,P131,Monitor Stand,10,3,28,30,840
50,P132,Mouse Pad,20,8,58,10,580
40,P133,Thermal Paste,15,5,50,5,250
30,P134,Cable Management Kit,12,4,34,15,510
20,P135,WiFi Adapter,8,3,23,20,460
15,P136,External DVD Drive,6,2,17,50,850
25,P137,Printer Cable,10,4,29,5,145
40,P138,Keyboard Cleaner,18,9,49,8,392
30,P139,Laptop Cooling Pad,15,6,39,20,780
35,P140,USB Hub,12,4,31,15,465
25,P141,Anti-Glare Screen Protector,8,3,28,10,280
20,P142,USB-C Adapter,10,4,24,15,360
30,P143,Laptop Sleeve,12,5,37,20,740
40,P144,Wireless Charger,18,7,51,30,1530
50,P145,USB-C Cable,20,9,61,8,488
25,P146,Gaming Desk,10,3,28,150,4200

In [65]:
data.iloc[5:20:1]

,Excel Sample Data,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
5,P102,Monitor,40,15,5,50,500,25000
6,P103,Keyboard,60,25,15,70,50,3500
7,P104,Headphones,30,10,3,37,100,3700
8,P105,Smartphone,70,30,20,80,900,72000
9,P106,Tablet,45,18,8,55,700,38500
10,P107,Router,55,22,12,65,150,9750
11,P108,External Hard Drive,25,12,5,32,200,6400
12,P109,Wireless Earbuds,35,15,7,43,80,3440
13,P110,Webcam,40,20,10,50,60,3000
14,P111,Desk Chair,20,8,3,25,150,3750
15,P112,Desk Lamp,30,15,7,38,30,1140
16,P113,USB Flash Drive,50,25,12,63,20,1260
17,P114,Ethernet Cable,60,30,15,75,10,750
18,P115,Power Strip,40,20,8,52,25,1300
19,P116,Wireless Mouse,35,15,5,45,40,1800

In [81]:
data.loc[3:10,["Unnamed: 2","Unnamed: 3"]]

         Unnamed: 2           Unnamed: 3
3   Opening \nStock  Purchase/\nStock in
4                50                   20
5                40                   15
6                60                   25
7                30                   10
8                70                   30
9                45                   18
10               55                   22